// This file is auto-generated by @hey-api/openapi-ts

export type AssignmentInfo = {
    unit_id: string;
    title: string;
    passage_count?: number;
    assign_reading?: (boolean | null);
    assign_repeat?: (boolean | null);
    assign_qa?: (boolean | null);
};

/**
 * 按题指派的单条题目引用：三种题型互相独立，各自成题。
 */
export type AssignmentItemIn = {
    type: string;
    id: string;
};

export type AssignmentRequest = {
    unit_id?: (string | null);
    assign_reading?: (boolean | null);
    assign_repeat?: (boolean | null);
    assign_qa?: (boolean | null);
    items?: (Array<AssignmentItemIn> | null);
    title?: (string | null);
    is_exam?: boolean;
    time_limit_minutes?: (number | null);
};

export type AttemptPublic = {
    id: string;
    item_type: string;
    item_id: string;
    student_id?: (string | null);
    session_id?: (string | null);
    status: string;
    engine: string;
    duration_s: number;
    retry_count?: number;
    transcript?: (string | null);
    completeness?: (number | null);
    fluency?: (number | null);
    accuracy?: (number | null);
    overall?: (number | null);
    advice?: (Array<(string)> | null);
    vocab?: ({
    [key: string]: unknown;
} | null);
    rubric?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    created_at?: (string | null);
};

export type AudioUrlResult = {
    audio_url: string;
};

export type AutoSplitResult = {
    created: number;
};

export type BadgePublic = {
    key: string;
    label: string;
    description: string;
    awarded_at?: (string | null);
};

export type BatchFailItem = {
    index: number;
    reason: string;
};

export type BatchQuestionCreate = {
    band?: string;
    items: Array<BatchQuestionItem>;
};

/**
 * 批量录入的单条：空文本/秒数越界等校验放处理器里逐条做，
 * 不在模型层拦——否则一条非法会把整批 422 掉。
 */
export type BatchQuestionItem = {
    text?: string;
    translation?: (string | null);
    suggested_seconds?: number;
};

export type BatchQuestionResult = {
    created: number;
    failed: Array<BatchFailItem>;
};

export type BoardData = {
    classroom_code: string;
    classroom_name: string;
    classroom_grade?: (string | null);
    teaching_goal?: (string | null);
    class_size: number;
    engine?: string;
    assignment?: (AssignmentInfo | null);
    assigned_items?: (Array<{
    [key: string]: (string);
}> | null);
    current_exercise?: (ClassroomExercisePublic | null);
    submitted_count: number;
    completed_count: number;
    pending_count: number;
    students: Array<BoardStudent>;
    items: Array<BoardItem>;
};

export type BoardItem = {
    item_id: string;
    type: string;
    status: string;
    overall?: (number | null);
    attempt_id?: (string | null);
};

export type BoardStudent = {
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    done_count: number;
    total_count: number;
    repeat_avg?: (number | null);
    question_avg?: (number | null);
    has_pending: boolean;
    round_status?: string;
    inactive_days7?: boolean;
    xp?: number;
    streak_days?: number;
    items: Array<BoardItem>;
    exam_tab_switches?: (number | null);
    exam_time_used_seconds?: (number | null);
    exam_ended?: (boolean | null);
};

export type Body_admin_import_wordlist_csv = {
    file: string;
};

export type Body_admin_upload_standard_audio = {
    file: string;
};

export type Body_attempts_create_attempt_upload = {
    /**
     * 浏览器 MediaRecorder 录制的音频
     */
    audio: string;
    item_type: string;
    item_id: string;
    /**
     * 录音时长（秒）
     */
    duration_s: number;
    session_id?: (string | null);
    /**
     * 幂等键：重传不重复创建
     */
    idempotency_key?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_vocab_levels_vocab_level_import_confirm = {
    file: string;
    level: string;
    source_label: string;
};

export type Body_vocab_levels_vocab_level_import_preview = {
    file: string;
    level: string;
    source_label: string;
};

export type Body_vocabulary_import_vocab_preview = {
    file: string;
};

export type BulkResetResult = {
    reset: number;
    rows: Array<StudentResetRow>;
};

export type ClassroomCreate = {
    name?: string;
    grade?: (string | null);
    teaching_goal?: (string | null);
    class_size?: number;
};

export type ClassroomExercisePublic = {
    id: string;
    classroom_id: string;
    version_no: number;
    title: string;
    status: string;
    item_count: number;
    created_at?: (string | null);
    published_at?: (string | null);
    archived_at?: (string | null);
    is_exam?: boolean;
    time_limit_minutes?: (number | null);
};

export type ClassroomPublic = {
    id: string;
    code: string;
    name: string;
    grade?: (string | null);
    teaching_goal?: (string | null);
    class_size: number;
    is_active: boolean;
    unlock_all?: boolean;
    owner_id?: (string | null);
    assign_reading?: (boolean | null);
    assign_repeat?: (boolean | null);
    assign_qa?: (boolean | null);
    current_exercise_id?: (string | null);
    created_at?: (string | null);
};

export type ClassroomUpdate = {
    name?: (string | null);
    grade?: (string | null);
    teaching_goal?: (string | null);
    unlock_all?: (boolean | null);
    owner_id?: (string | null);
    is_active?: (boolean | null);
};

export type DraftQuestionOut = {
    text: string;
    suggested_seconds: number;
};

/**
 * 考试态信息（学生端倒计时与锁题、教师端监考）。
 */
export type ExamStatus = {
    time_limit_minutes: number;
    remaining_seconds: number;
    started: boolean;
    ended: boolean;
    tab_switch_count?: number;
};

export type ExamViolationRequest = {
    session_id: string;
};

export type ExamViolationResult = {
    tab_switch_count: number;
};

/**
 * 单次练习按学生的结果行（发布历史结果页）。
 */
export type ExerciseStudentResult = {
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    done_count: number;
    total_count: number;
    has_pending: boolean;
    items: Array<BoardItem>;
    exam_tab_switches?: (number | null);
    exam_time_used_seconds?: (number | null);
    exam_ended?: (boolean | null);
};

export type ExploreRequest = {
    unit_id: string;
};

export type ExploreStarted = {
    session_id: string;
    unit_title: string;
};

export type FrameFavoriteRequest = {
    frame_id: string;
};

export type GamificationInfo = {
    xp?: number;
    streak_days?: number;
    session_stars?: (number | null);
    badges?: Array<BadgePublic>;
};

export type GenerateRequest = {
    band?: string;
    count?: number;
    hint?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LearningPath = {
    classroom_code: string;
    unlock_all: boolean;
    assignment?: (AssignmentInfo | null);
    units: Array<PathUnit>;
};

export type ListenRequest = {
    session_id: string;
    item_id: string;
};

export type ListenResult = {
    listen_used: number;
    replay_limit: number;
};

export type LoginOptions = {
    demo_enabled: boolean;
    registration_enabled: boolean;
    password_recovery_enabled: boolean;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NextQuestion = {
    question?: (ScenarioQuestionPublic | null);
    exhausted?: boolean;
};

export type PassageCreate = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    slug?: (string | null);
    unit_id?: (string | null);
};

export type PassagePublic = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    id: string;
    slug: string;
    unit_id?: (string | null);
    created_at?: (string | null);
};

export type PassageSplitResult = {
    created: number;
    passage_ids?: Array<(string)>;
    original_deactivated?: boolean;
};

/**
 * 更新篇目请求：缺省不修改；translation/audio_url/unit_id 可 null 清空。
 */
export type PassageUpdate = {
    title?: (string | null);
    topic?: (string | null);
    cefr_band?: (string | null);
    text?: (string | null);
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: (number | null);
    is_active?: (boolean | null);
    unit_id?: (string | null);
};

export type PassageWithSentences = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    id: string;
    slug: string;
    unit_id?: (string | null);
    created_at?: (string | null);
    sentences?: Array<RepeatSentence>;
};

export type PathUnit = {
    unit_id: string;
    order_index: number;
    title: string;
    topic: string;
    rounds_done?: number;
    best_stars?: (number | null);
    locked?: boolean;
    passage_id?: (string | null);
};

export type PlanAttempt = {
    item_id: string;
    attempt_id: string;
    status: string;
    overall?: (number | null);
    completeness?: (number | null);
    fluency?: (number | null);
    transcript?: (string | null);
    advice?: (Array<(string)> | null);
    vocab?: ({
    [key: string]: unknown;
} | null);
    rubric?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
};

export type PlanItem = {
    type: string;
    id: string;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds: number;
    band?: (string | null);
    replay_limit?: (number | null);
    listen_used?: (number | null);
    exam_kind?: (string | null);
    exam_level?: (string | null);
    cue_card_bullets?: (Array<(string)> | null);
    prep_seconds?: (number | null);
    frames?: (Array<SentenceFramePublic> | null);
};

/**
 * 题库全局视图：带上主题，供管理端筛选/搜索。
 */
export type QuestionBankOut = {
    id: string;
    scenario_id: string;
    topic: string;
    band: string;
    order_index: number;
    text: string;
    translation?: (string | null);
    suggested_seconds: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
    cue_card_bullets?: (Array<(string)> | null);
    prep_seconds?: (number | null);
};

/**
 * 新建问法请求：scenario_id 兼容旧客户端，以路径参数为准。
 */
export type QuestionCreate = {
    scenario_id?: (string | null);
    band?: string;
    order_index?: number;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
    cue_card_bullets?: (Array<(string)> | null);
    prep_seconds?: (number | null);
};

export type QuestionUpdate = {
    band?: (string | null);
    text?: (string | null);
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: (number | null);
    order_index?: (number | null);
    exam_kind?: (string | null);
    exam_level?: (string | null);
    cue_card_bullets?: (Array<(string)> | null);
    prep_seconds?: (number | null);
};

export type RepeatSentence = {
    id?: string;
    passage_id?: (string | null);
    order_index: number;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    replay_limit?: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
    created_at?: (string | null);
};

/**
 * 新建情景请求：主题必填且非空。
 */
export type ScenarioCreate = {
    topic: string;
    is_active?: boolean;
};

/**
 * list_scenarios 的响应形状：情景 + 其问法列表。
 */
export type ScenarioOut = {
    id: string;
    topic: string;
    is_active: boolean;
    questions: Array<ScenarioQuestionPublic>;
};

export type ScenarioQuestionPublic = {
    id: string;
    band: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
    cue_card_bullets?: (Array<(string)> | null);
    prep_seconds?: (number | null);
};

export type ScenarioUpdate = {
    topic?: (string | null);
    is_active?: (boolean | null);
};

/**
 * 新建复述句请求（独立创建或挂篇目）。
 */
export type SentenceCreate = {
    passage_id?: (string | null);
    order_index?: number;
    text: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    replay_limit?: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
};

export type SentenceFrameBatchIssue = {
    index: number;
    reason: string;
};

/**
 * 批量导入的单条：校验放处理器逐条做，避免一条非法整批 422。
 */
export type SentenceFrameBatchItem = {
    level?: string;
    purpose?: string;
    exam_kind?: (string | null);
    text_en?: string;
    text_zh?: string;
};

export type SentenceFrameBatchResult = {
    created: number;
    skipped_duplicates: number;
    invalid: Array<SentenceFrameBatchIssue>;
};

export type SentenceFrameCreate = {
    level: string;
    purpose: string;
    exam_kind?: (string | null);
    text_en: string;
    text_zh: string;
    status?: string;
};

export type SentenceFramePublic = {
    id: string;
    level: string;
    purpose: string;
    exam_kind?: (string | null);
    text_en: string;
    text_zh: string;
    status?: string;
    favorited?: boolean;
};

export type SentenceFrameUpdate = {
    level?: (string | null);
    purpose?: (string | null);
    exam_kind?: (string | null);
    text_en?: (string | null);
    text_zh?: (string | null);
    status?: (string | null);
};

/**
 * 更新复述句请求：缺省不修改；passage_id/translation/audio_url 可 null 清空。
 */
export type SentenceUpdate = {
    passage_id?: (string | null);
    order_index?: (number | null);
    text?: (string | null);
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: (number | null);
    replay_limit?: (number | null);
    exam_kind?: (string | null);
    exam_level?: (string | null);
};

/**
 * 平铺复述句库视图：带所属篇目标题（独立句为 null）。
 */
export type SentenceWithPassage = {
    id?: string;
    passage_id?: (string | null);
    order_index?: number;
    text?: string;
    translation?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: number;
    replay_limit?: number;
    exam_kind?: (string | null);
    exam_level?: (string | null);
    created_at?: (string | null);
    passage_title?: (string | null);
};

export type StudentAccountOut = {
    student: StudentPublic;
    username?: (string | null);
    full_name?: (string | null);
    must_change_password?: boolean;
};

export type StudentImportLine = {
    username: string;
    full_name: string;
};

export type StudentImportRequest = {
    classroom_id: string;
    lines: Array<StudentImportLine>;
};

export type StudentImportResult = {
    created: number;
    merged: number;
    skipped: number;
    rows: Array<StudentImportRow>;
};

/**
 * 导入结果行：初始密码只在本次响应返回一次，不入日志。
 */
export type StudentImportRow = {
    username: string;
    full_name: string;
    initial_password?: (string | null);
    student_id?: (string | null);
    merged_existing?: boolean;
    error?: (string | null);
};

export type StudentJoin = {
    display_name?: (string | null);
};

export type StudentPublic = {
    id: string;
    display_name: string;
    suffix?: (string | null);
    current_band: string;
    classroom_id: string;
    user_id?: (string | null);
};

export type StudentResetRow = {
    username: string;
    full_name?: (string | null);
    student_id: string;
    new_password: string;
};

export type TodayPlan = {
    session_id: string;
    classroom_code: string;
    band: string;
    items: Array<PlanItem>;
    attempts: Array<PlanAttempt>;
    questions_exhausted?: boolean;
    gamification?: (GamificationInfo | null);
    assigned_unit_title?: (string | null);
    exam?: (ExamStatus | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrailData = {
    classroom_code: string;
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    sessions: Array<TrailSession>;
    band_change?: (string | null);
    total_minutes?: number;
    vocab_counts?: {
        [key: string]: (number);
    };
};

export type TrailSession = {
    date: string;
    speaking_avg?: (number | null);
    repeat_completeness_avg?: (number | null);
    vocab_cefr?: (string | null);
    attempt_count?: number;
};

export type TtsRequest = {
    text: string;
    voice?: (string | null);
};

export type UnitCreate = {
    order_index?: number;
    title: string;
    topic: string;
    is_active?: boolean;
};

export type UnitPublic = {
    id: string;
    order_index: number;
    title: string;
    topic: string;
    is_active: boolean;
    passage_count?: number;
};

export type UnitUpdate = {
    order_index?: (number | null);
    title?: (string | null);
    topic?: (string | null);
    is_active?: (boolean | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: string;
    username?: (string | null);
    must_change_password?: boolean;
    password: string;
};

export type UserPublic = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: string;
    username?: (string | null);
    must_change_password?: boolean;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
    role?: (string | null);
    username?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VocabularyAnswerRequest = {
    item_index: number;
    prompt_type?: string;
    answer: string;
    idempotency_key?: (string | null);
};

export type VocabularyAnswerResult = {
    item_index: number;
    attempt_no: number;
    is_correct: boolean;
    correct_spelling: string;
    meaning_zh: string;
    session_status: string;
    answered_count: number;
    correct_first_count: number;
};

export type VocabularyAssignmentCreate = {
    title?: (string | null);
    book_id?: (string | null);
    word_ids?: (Array<(string)> | null);
    prompt_types?: Array<(string)>;
    mode?: string;
    due_at?: (string | null);
};

export type VocabularyAssignmentPublic = {
    id: string;
    classroom_id: string;
    title: string;
    mode: string;
    prompt_types?: Array<(string)>;
    status: string;
    version_no: number;
    word_count: number;
    due_at?: (string | null);
    published_at?: (string | null);
    archived_at?: (string | null);
    created_by?: (string | null);
};

export type VocabularyBookCreate = {
    title: string;
    description?: (string | null);
    scope?: string;
    classroom_id?: (string | null);
    words?: Array<VocabularyWordIn>;
};

export type VocabularyBookDetail = {
    id: string;
    title: string;
    description?: (string | null);
    scope: string;
    classroom_id?: (string | null);
    owner_id?: (string | null);
    status: string;
    word_count?: number;
    created_at?: (string | null);
    words?: Array<VocabularyWordPublic>;
};

export type VocabularyBookPublic = {
    id: string;
    title: string;
    description?: (string | null);
    scope: string;
    classroom_id?: (string | null);
    owner_id?: (string | null);
    status: string;
    word_count?: number;
    created_at?: (string | null);
};

export type VocabularyBookUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (string | null);
};

/**
 * GET /classes/{code}/vocabulary/results。
 */
export type VocabularyClassResults = {
    assignment?: (VocabularyAssignmentPublic | null);
    target_count?: number;
    completed_count?: number;
    in_progress_count?: number;
    not_started_count?: number;
    students?: Array<VocabularyStudentResultRow>;
    words?: Array<VocabularyWordStatRow>;
};

/**
 * 从五级词库导入教学词条到词库（仅已核对、有释义的词条）。
 */
export type VocabularyFromLevelsRequest = {
    level: string;
    book_id?: (string | null);
    classroom_id?: (string | null);
    new_book_title?: (string | null);
    limit?: number;
};

/**
 * 建库/并库结果 + 本次从分级库转入的统计。
 */
export type VocabularyFromLevelsResult = {
    id: string;
    title: string;
    description?: (string | null);
    scope: string;
    classroom_id?: (string | null);
    owner_id?: (string | null);
    status: string;
    word_count?: number;
    created_at?: (string | null);
    words?: Array<VocabularyWordPublic>;
    created_count?: number;
    skipped_existing?: number;
    remaining_count?: number;
};

export type VocabularyImportIssue = {
    line: number;
    reason: string;
};

export type VocabularyImportPreview = {
    rows: Array<VocabularyImportRow>;
    invalid: Array<VocabularyImportIssue>;
    duplicates: Array<VocabularyImportIssue>;
};

/**
 * 导入预览里解析成功的一行（已规范化）。
 */
export type VocabularyImportRow = {
    line: number;
    word: VocabularyWordIn;
};

export type VocabularyLevelEntryPublic = {
    id: string;
    headword: string;
    level: string;
    sense_no: number;
    part_of_speech?: (string | null);
    meaning_zh?: (string | null);
    is_phrase?: boolean;
    needs_review?: boolean;
    note?: (string | null);
    sources?: Array<(string)>;
    status?: string;
};

/**
 * 人工核对修正：缺省不修改；needs_review=False 即「已核对」。
 */
export type VocabularyLevelEntryUpdate = {
    part_of_speech?: (string | null);
    meaning_zh?: (string | null);
    note?: (string | null);
    needs_review?: (boolean | null);
    status?: (string | null);
};

/**
 * 导入预览的问题行。kind: invalid | duplicate_in_file | cross_level_conflict
 */
export type VocabularyLevelImportIssue = {
    kind: string;
    line: number;
    headword: string;
    reason: string;
    existing_level?: (string | null);
};

export type VocabularyLevelImportPreview = {
    level: string;
    source_label: string;
    valid_rows: Array<VocabularyWordIn>;
    invalid: Array<VocabularyLevelImportIssue>;
    duplicates_in_file: Array<VocabularyLevelImportIssue>;
    cross_level_conflicts: Array<VocabularyLevelImportIssue>;
    new_count: number;
    merge_count: number;
    counts_after: Array<VocabularyLevelLevelCount>;
};

export type VocabularyLevelImportResult = {
    imported_new: number;
    merged_existing: number;
    skipped_invalid: number;
    counts: Array<VocabularyLevelLevelCount>;
};

export type VocabularyLevelLevelCount = {
    level: string;
    entry_count?: number;
    phrase_count?: number;
    needs_review_count?: number;
};

export type VocabularyLevelStats = {
    levels?: Array<VocabularyLevelLevelCount>;
    total_entries?: number;
    total_sources?: number;
};

/**
 * 学生侧轮次摘要：轮次回看入口（只读查看指定轮）。
 */
export type VocabularyRoundSummaryRow = {
    round_no: number;
    status: string;
    answered_count: number;
    correct_first_count: number;
    submitted_at?: (string | null);
};

/**
 * 创建/恢复作答会话：缺省 assignment_id = 聚焦任务。
 */
export type VocabularySessionCreate = {
    assignment_id?: (string | null);
    round?: (string | null);
};

/**
 * 学生任务列表条目：进度与时间（逾期）两维分别展示。
 */
export type VocabularyStudentAssignment = {
    assignment_id: string;
    title: string;
    word_count: number;
    due_at?: (string | null);
    progress?: string;
    overdue?: boolean;
    answered_count?: number;
    correct_first_count?: number;
    round_count?: number;
};

/**
 * 教师结果面板的学生行（按目标名单，含未开始）。
 *
 * 任务成绩锁定首轮（round_no=1 的首答）；rounds 为各轮次独立汇总，
 * 供教师查看复习轮，不参与完成度与正确率统计。
 */
export type VocabularyStudentResultRow = {
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    status: string;
    answered_count: number;
    correct_first_count: number;
    total_count: number;
    submitted_at?: (string | null);
    round_count?: number;
    rounds?: Array<VocabularyStudentRoundRow>;
};

/**
 * 单个轮次的独立汇总（首轮=任务成绩；复习轮单独记录）。
 */
export type VocabularyStudentRoundRow = {
    round_no: number;
    status: string;
    answered_count: number;
    correct_first_count: number;
    submitted_at?: (string | null);
};

/**
 * 教师任务列表行：任务 + 名单进度汇总（首轮首答口径，逾期独立计数）。
 */
export type VocabularyTeacherAssignmentRow = {
    assignment: VocabularyAssignmentPublic;
    target_count?: number;
    completed_count?: number;
    in_progress_count?: number;
    not_started_count?: number;
    overdue_count?: number;
};

/**
 * 学生题单条目：未作答的词不透露拼写（headword=None）。
 */
export type VocabularyTodayItem = {
    item_index: number;
    prompt_type: string;
    part_of_speech?: (string | null);
    meaning_zh: string;
    meaning_en?: (string | null);
    audio_url?: (string | null);
    headword?: (string | null);
    answered?: boolean;
    is_correct?: (boolean | null);
    attempt_count?: number;
};

/**
 * GET /classes/{code}/vocabulary/today 的学生视图。
 */
export type VocabularyTodayPlan = {
    assignment?: (VocabularyAssignmentPublic | null);
    session_id?: (string | null);
    session_status?: (string | null);
    session_round?: (number | null);
    session_closed_reason?: (string | null);
    items?: Array<VocabularyTodayItem>;
    answered_count?: number;
    correct_first_count?: number;
    wrong_word_count?: number;
    rounds?: Array<VocabularyRoundSummaryRow>;
    assignments?: Array<VocabularyStudentAssignment>;
};

/**
 * 创建/导入词条的请求体（词库内新增词）。
 */
export type VocabularyWordIn = {
    headword: string;
    part_of_speech?: (string | null);
    meaning_zh: string;
    meaning_en?: (string | null);
    accepted_spellings?: (Array<(string)> | null);
    example_en?: (string | null);
    audio_url?: (string | null);
};

export type VocabularyWordMisspelling = {
    answer: string;
    count: number;
};

export type VocabularyWordPublic = {
    id: string;
    headword: string;
    part_of_speech?: (string | null);
    meaning_zh: string;
    meaning_en?: (string | null);
    accepted_spellings?: (Array<(string)> | null);
    example_en?: (string | null);
    audio_url?: (string | null);
    status?: string;
    level?: (string | null);
    all_levels?: Array<(string)>;
};

/**
 * 逐词错误分布（教师据此安排复习）。
 */
export type VocabularyWordStatRow = {
    item_index: number;
    word_id: string;
    headword: string;
    meaning_zh: string;
    answered_count: number;
    correct_first_count: number;
    error_count: number;
    misspellings?: Array<VocabularyWordMisspelling>;
};

/**
 * 编辑词条：缺省不修改；可空字段传 null 清空。
 */
export type VocabularyWordUpdate = {
    part_of_speech?: (string | null);
    meaning_zh?: (string | null);
    meaning_en?: (string | null);
    accepted_spellings?: (Array<(string)> | null);
    example_en?: (string | null);
    audio_url?: (string | null);
    status?: (string | null);
};

/**
 * 错词本条目：首答判错的词，按快照内容展示。
 */
export type VocabularyWrongWordItem = {
    word_id: string;
    headword: string;
    meaning_zh: string;
    part_of_speech?: (string | null);
    wrong_count: number;
    last_wrong_at?: (string | null);
};

export type VocabularyWrongWords = {
    classroom_code: string;
    items?: Array<VocabularyWrongWordItem>;
};

export type WordlistImportResult = {
    imported: number;
    invalid_rows?: Array<(number)>;
};

export type WordlistStats = {
    total: number;
    by_band: {
        [key: string]: (number);
    };
    name?: (string | null);
};

export type AdminListPassagesResponse = (Array<PassageWithSentences>);

export type AdminCreatePassageData = {
    requestBody: PassageCreate;
};

export type AdminCreatePassageResponse = (PassagePublic);

export type AdminUpdatePassageData = {
    passageId: string;
    requestBody: PassageUpdate;
};

export type AdminUpdatePassageResponse = (PassagePublic);

export type AdminDeletePassageData = {
    passageId: string;
};

export type AdminDeletePassageResponse = ({
    [key: string]: (string);
});

export type AdminCreateSentenceData = {
    passageId: string;
    requestBody: SentenceCreate;
};

export type AdminCreateSentenceResponse = (RepeatSentence);

export type AdminListSentencesFlatData = {
    /**
     * 考试题型过滤
     */
    examKind?: (string | null);
    /**
     * 考试级别过滤
     */
    examLevel?: (string | null);
};

export type AdminListSentencesFlatResponse = (Array<SentenceWithPassage>);

export type AdminCreateSentenceStandaloneData = {
    requestBody: SentenceCreate;
};

export type AdminCreateSentenceStandaloneResponse = (RepeatSentence);

export type AdminUpdateSentenceData = {
    requestBody: SentenceUpdate;
    sentenceId: string;
};

export type AdminUpdateSentenceResponse = (RepeatSentence);

export type AdminDeleteSentenceData = {
    sentenceId: string;
};

export type AdminDeleteSentenceResponse = ({
    [key: string]: (string);
});

export type AdminListScenariosResponse = (Array<ScenarioOut>);

export type AdminCreateScenarioData = {
    requestBody: ScenarioCreate;
};

export type AdminCreateScenarioResponse = (unknown);

export type AdminDeleteScenarioData = {
    scenarioId: string;
};

export type AdminDeleteScenarioResponse = ({
    [key: string]: (string);
});

export type AdminUpdateScenarioData = {
    requestBody: ScenarioUpdate;
    scenarioId: string;
};

export type AdminUpdateScenarioResponse = (unknown);

export type AdminCreateQuestionData = {
    requestBody: QuestionCreate;
    scenarioId: string;
};

export type AdminCreateQuestionResponse = (ScenarioQuestionPublic);

export type AdminDeleteQuestionData = {
    questionId: string;
};

export type AdminDeleteQuestionResponse = ({
    [key: string]: (string);
});

export type AdminUpdateQuestionData = {
    questionId: string;
    requestBody: QuestionUpdate;
};

export type AdminUpdateQuestionResponse = (ScenarioQuestionPublic);

export type AdminListQuestionBankData = {
    /**
     * A2/B1/B2
     */
    band?: (string | null);
    /**
     * 考试题型过滤
     */
    examKind?: (string | null);
    /**
     * 考试级别过滤
     */
    examLevel?: (string | null);
    /**
     * 题目/中文提示关键词
     */
    q?: (string | null);
    /**
     * 按主题精确过滤
     */
    topic?: (string | null);
};

export type AdminListQuestionBankResponse = (Array<QuestionBankOut>);

export type AdminCreateQuestionsBatchData = {
    requestBody: BatchQuestionCreate;
    scenarioId: string;
};

export type AdminCreateQuestionsBatchResponse = (BatchQuestionResult);

export type AdminWordlistStatsResponse = (WordlistStats);

export type AdminImportWordlistCsvData = {
    formData: Body_admin_import_wordlist_csv;
};

export type AdminImportWordlistCsvResponse = (WordlistImportResult);

export type AdminListUnitsResponse = (Array<UnitPublic>);

export type AdminCreateUnitData = {
    requestBody: UnitCreate;
};

export type AdminCreateUnitResponse = (UnitPublic);

export type AdminUpdateUnitData = {
    requestBody: UnitUpdate;
    unitId: string;
};

export type AdminUpdateUnitResponse = (UnitPublic);

export type AdminDeleteUnitData = {
    unitId: string;
};

export type AdminDeleteUnitResponse = ({
    [key: string]: (string);
});

export type AdminListTopicsResponse = (Array<(string)>);

export type AdminListClassroomsResponse = (Array<ClassroomPublic>);

export type AdminDeactivateClassroomData = {
    classroomId: string;
};

export type AdminDeactivateClassroomResponse = ({
    [key: string]: (string);
});

export type AdminUpdateClassroomData = {
    classroomId: string;
    requestBody: ClassroomUpdate;
};

export type AdminUpdateClassroomResponse = (ClassroomPublic);

export type AdminGenerateQuestionsData = {
    requestBody: GenerateRequest;
    scenarioId: string;
};

export type AdminGenerateQuestionsResponse = (Array<DraftQuestionOut>);

export type AdminAutoSplitSentencesData = {
    passageId: string;
    targetCount?: number;
};

export type AdminAutoSplitSentencesResponse = (AutoSplitResult);

export type AdminSplitPassageIntoReadingsData = {
    passageId: string;
};

export type AdminSplitPassageIntoReadingsResponse = (PassageSplitResult);

export type AdminGenerateStandardAudioData = {
    requestBody: TtsRequest;
};

export type AdminGenerateStandardAudioResponse = (AudioUrlResult);

export type AdminUploadStandardAudioData = {
    formData: Body_admin_upload_standard_audio;
};

export type AdminUploadStandardAudioResponse = (AudioUrlResult);

export type AdminListSentenceFramesData = {
    /**
     * 题型筛选
     */
    examKind?: (string | null);
    /**
     * 五级筛选
     */
    level?: (string | null);
    /**
     * 表达用途筛选
     */
    purpose?: (string | null);
};

export type AdminListSentenceFramesResponse = (Array<SentenceFramePublic>);

export type AdminCreateSentenceFrameData = {
    requestBody: SentenceFrameCreate;
};

export type AdminCreateSentenceFrameResponse = (SentenceFramePublic);

export type AdminUpdateSentenceFrameData = {
    frameId: string;
    requestBody: SentenceFrameUpdate;
};

export type AdminUpdateSentenceFrameResponse = (SentenceFramePublic);

export type AdminDeleteSentenceFrameData = {
    frameId: string;
};

export type AdminDeleteSentenceFrameResponse = ({
    [key: string]: (string);
});

export type AdminCreateSentenceFramesBatchData = {
    requestBody: Array<SentenceFrameBatchItem>;
};

export type AdminCreateSentenceFramesBatchResponse = (SentenceFrameBatchResult);

export type AttemptsCreateAttemptUploadData = {
    formData: Body_attempts_create_attempt_upload;
};

export type AttemptsCreateAttemptUploadResponse = (AttemptPublic);

export type AttemptsReadAttemptData = {
    attemptId: string;
};

export type AttemptsReadAttemptResponse = (AttemptPublic);

export type AttemptsReadAttemptAudioData = {
    attemptId: string;
};

export type AttemptsReadAttemptAudioResponse = (unknown);

export type AudioReadContentAudioData = {
    filename: string;
};

export type AudioReadContentAudioResponse = (unknown);

export type ClassesListMyClassroomsResponse = (Array<ClassroomPublic>);

export type ClassesCreateClassData = {
    requestBody: ClassroomCreate;
};

export type ClassesCreateClassResponse = (ClassroomPublic);

export type ClassesDeleteClassData = {
    code: string;
};

export type ClassesDeleteClassResponse = ({
    [key: string]: (string);
});

export type ClassesJoinClassData = {
    code: string;
    requestBody: StudentJoin;
};

export type ClassesJoinClassResponse = (StudentPublic);

export type ClassesReadTodayPlanData = {
    code: string;
    sessionId?: (string | null);
};

export type ClassesReadTodayPlanResponse = (TodayPlan);

export type ClassesReadNextQuestionData = {
    code: string;
    excludeIds?: (Array<(string)> | null);
    sessionId?: (string | null);
};

export type ClassesReadNextQuestionResponse = (NextQuestion);

export type ClassesReadClassBoardData = {
    code: string;
};

export type ClassesReadClassBoardResponse = (BoardData);

export type ClassesReadStudentTrailData = {
    code: string;
    /**
     * 查询最近多少天的轨迹
     */
    days?: number;
    /**
     * 教师查看指定学生；学生查看自己时省略
     */
    studentId?: (string | null);
};

export type ClassesReadStudentTrailResponse = (TrailData);

export type ClassesReadLearningPathData = {
    code: string;
};

export type ClassesReadLearningPathResponse = (LearningPath);

export type ClassesReportExamViolationData = {
    code: string;
    requestBody: ExamViolationRequest;
};

export type ClassesReportExamViolationResponse = (ExamViolationResult);

export type ClassesRecordListenData = {
    code: string;
    requestBody: ListenRequest;
};

export type ClassesRecordListenResponse = (ListenResult);

export type ClassesListClassroomExercisesData = {
    code: string;
};

export type ClassesListClassroomExercisesResponse = (Array<ClassroomExercisePublic>);

export type ClassesReadExerciseResultsData = {
    code: string;
    exerciseId: string;
};

export type ClassesReadExerciseResultsResponse = (Array<ExerciseStudentResult>);

export type ClassesSetAssignmentData = {
    code: string;
    requestBody: AssignmentRequest;
};

export type ClassesSetAssignmentResponse = ((AssignmentInfo | null));

export type ClassesStartExploreData = {
    code: string;
    requestBody: ExploreRequest;
};

export type ClassesStartExploreResponse = (ExploreStarted);

export type ClassesListMyFrameFavoritesData = {
    code: string;
};

export type ClassesListMyFrameFavoritesResponse = (Array<SentenceFramePublic>);

export type ClassesAddFrameFavoriteData = {
    code: string;
    requestBody: FrameFavoriteRequest;
};

export type ClassesAddFrameFavoriteResponse = (Array<SentenceFramePublic>);

export type ClassesRemoveFrameFavoriteData = {
    code: string;
    frameId: string;
};

export type ClassesRemoveFrameFavoriteResponse = (Array<SentenceFramePublic>);

export type LoginReadLoginOptionsResponse = (LoginOptions);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginLoginDemoResponse = (Token);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type StudentsImportStudentsData = {
    requestBody: StudentImportRequest;
};

export type StudentsImportStudentsResponse = (StudentImportResult);

export type StudentsListStudentsData = {
    classroomId: string;
};

export type StudentsListStudentsResponse = (Array<StudentAccountOut>);

export type StudentsResetStudentPasswordData = {
    studentId: string;
};

export type StudentsResetStudentPasswordResponse = ({
    [key: string]: (string);
});

export type StudentsRemoveStudentData = {
    studentId: string;
};

export type StudentsRemoveStudentResponse = ({
    [key: string]: (string);
});

export type StudentsBulkResetPasswordsData = {
    classroomId: string;
};

export type StudentsBulkResetPasswordsResponse = (BulkResetResult);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadyCheckResponse = (Message);

export type VocabLevelsVocabLevelStatsResponse = (VocabularyLevelStats);

export type VocabLevelsVocabLevelImportPreviewData = {
    formData: Body_vocab_levels_vocab_level_import_preview;
};

export type VocabLevelsVocabLevelImportPreviewResponse = (VocabularyLevelImportPreview);

export type VocabLevelsVocabLevelImportConfirmData = {
    formData: Body_vocab_levels_vocab_level_import_confirm;
};

export type VocabLevelsVocabLevelImportConfirmResponse = (VocabularyLevelImportResult);

export type VocabLevelsListVocabLevelEntriesData = {
    headword?: (string | null);
    level?: (string | null);
    limit?: number;
    needsReview?: (boolean | null);
    offset?: number;
};

export type VocabLevelsListVocabLevelEntriesResponse = (Array<VocabularyLevelEntryPublic>);

export type VocabLevelsUpdateVocabLevelEntryData = {
    entryId: string;
    requestBody: VocabularyLevelEntryUpdate;
};

export type VocabLevelsUpdateVocabLevelEntryResponse = (VocabularyLevelEntryPublic);

export type VocabLevelsListTeachingWordsByLevelData = {
    level: string;
    limit?: number;
    offset?: number;
};

export type VocabLevelsListTeachingWordsByLevelResponse = (Array<VocabularyWordPublic>);

export type VocabLevelsImportWordsFromLevelsData = {
    requestBody: VocabularyFromLevelsRequest;
};

export type VocabLevelsImportWordsFromLevelsResponse = (VocabularyFromLevelsResult);

export type VocabularyImportVocabPreviewData = {
    formData: Body_vocabulary_import_vocab_preview;
};

export type VocabularyImportVocabPreviewResponse = (VocabularyImportPreview);

export type VocabularyListBooksResponse = (Array<VocabularyBookPublic>);

export type VocabularyCreateBookData = {
    requestBody: VocabularyBookCreate;
};

export type VocabularyCreateBookResponse = (VocabularyBookDetail);

export type VocabularyReadBookData = {
    bookId: string;
    level?: (string | null);
};

export type VocabularyReadBookResponse = (VocabularyBookDetail);

export type VocabularyUpdateBookData = {
    bookId: string;
    requestBody: VocabularyBookUpdate;
};

export type VocabularyUpdateBookResponse = (VocabularyBookPublic);

export type VocabularyAddBookWordsData = {
    bookId: string;
    requestBody: Array<VocabularyWordIn>;
};

export type VocabularyAddBookWordsResponse = (VocabularyBookDetail);

export type VocabularyRemoveBookWordData = {
    bookId: string;
    wordId: string;
};

export type VocabularyRemoveBookWordResponse = (unknown);

export type VocabularyUpdateWordData = {
    requestBody: VocabularyWordUpdate;
    wordId: string;
};

export type VocabularyUpdateWordResponse = (VocabularyWordPublic);

export type VocabularyListAssignmentsData = {
    code: string;
};

export type VocabularyListAssignmentsResponse = (Array<VocabularyTeacherAssignmentRow>);

export type VocabularyPublishVocabAssignmentData = {
    code: string;
    requestBody: VocabularyAssignmentCreate;
};

export type VocabularyPublishVocabAssignmentResponse = (VocabularyAssignmentPublic);

export type VocabularyArchiveVocabAssignmentData = {
    assignmentId: string;
    code: string;
};

export type VocabularyArchiveVocabAssignmentResponse = (unknown);

export type VocabularyReadVocabResultsData = {
    assignmentId?: (string | null);
    code: string;
};

export type VocabularyReadVocabResultsResponse = (VocabularyClassResults);

export type VocabularyReadVocabTodayData = {
    assignmentId?: (string | null);
    code: string;
    roundNo?: (number | null);
};

export type VocabularyReadVocabTodayResponse = (VocabularyTodayPlan);

export type VocabularyStartVocabSessionData = {
    code: string;
    requestBody: VocabularySessionCreate;
};

export type VocabularyStartVocabSessionResponse = (unknown);

export type VocabularySubmitVocabAnswerData = {
    requestBody: VocabularyAnswerRequest;
    sessionId: string;
};

export type VocabularySubmitVocabAnswerResponse = (VocabularyAnswerResult);

export type VocabularyReadWrongWordsData = {
    code: string;
};

export type VocabularyReadWrongWordsResponse = (VocabularyWrongWords);