// This file is auto-generated by @hey-api/openapi-ts

export type AttemptPublic = {
    id: string;
    item_type: string;
    item_id: string;
    student_id?: (string | null);
    session_id?: (string | null);
    status: string;
    engine: string;
    duration_s: number;
    transcript?: (string | null);
    completeness?: (number | null);
    fluency?: (number | null);
    accuracy?: (number | null);
    overall?: (number | null);
    advice?: (Array<(string)> | null);
    vocab?: ({
    [key: string]: unknown;
} | null);
    rubric?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    created_at?: (string | null);
};

export type AudioUrlResult = {
    audio_url: string;
};

export type AutoSplitResult = {
    created: number;
};

export type BadgePublic = {
    key: string;
    label: string;
    description: string;
    awarded_at?: (string | null);
};

export type BoardData = {
    classroom_code: string;
    class_size: number;
    engine?: string;
    submitted_count: number;
    pending_count: number;
    band_distribution: {
        [key: string]: (number);
    };
    students: Array<BoardStudent>;
    items: Array<BoardItem>;
};

export type BoardItem = {
    item_id: string;
    type: string;
    status: string;
    overall?: (number | null);
    attempt_id?: (string | null);
};

export type BoardStudent = {
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    done_count: number;
    total_count: number;
    repeat_avg?: (number | null);
    question_avg?: (number | null);
    has_pending: boolean;
    current_band: string;
    inactive_days7?: boolean;
    xp?: number;
    streak_days?: number;
    items: Array<BoardItem>;
};

export type Body_admin_import_wordlist_csv = {
    file: string;
};

export type Body_admin_upload_standard_audio = {
    file: string;
};

export type Body_attempts_create_attempt_upload = {
    /**
     * 浏览器 MediaRecorder 录制的音频
     */
    audio: string;
    item_type: string;
    item_id: string;
    /**
     * 录音时长（秒）
     */
    duration_s: number;
    student_id?: (string | null);
    session_id?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClassroomCreate = {
    class_size?: number;
};

export type ClassroomPublic = {
    id: string;
    code: string;
    class_size: number;
    is_active: boolean;
    unlock_all?: boolean;
    created_at?: (string | null);
};

export type ClassroomUpdate = {
    unlock_all?: (boolean | null);
};

export type DraftQuestionOut = {
    text: string;
    suggested_seconds: number;
};

export type GamificationInfo = {
    xp?: number;
    streak_days?: number;
    session_stars?: (number | null);
    badges?: Array<BadgePublic>;
};

export type GenerateRequest = {
    band: string;
    count?: number;
    hint?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LearningPath = {
    classroom_code: string;
    unlock_all: boolean;
    units: Array<PathUnit>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NextQuestion = {
    question?: (ScenarioQuestionPublic | null);
    exhausted?: boolean;
};

export type PassageCreate = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    slug: string;
    unit_id?: (string | null);
};

export type PassagePublic = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    id: string;
    slug: string;
    created_at?: (string | null);
};

export type PassageWithSentences = {
    title: string;
    topic?: string;
    cefr_band?: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds?: number;
    is_active?: boolean;
    id: string;
    slug: string;
    created_at?: (string | null);
    sentences?: Array<RepeatSentence>;
};

export type PathUnit = {
    unit_id: string;
    order_index: number;
    title: string;
    topic: string;
    rounds_done?: number;
    best_stars?: (number | null);
    locked?: boolean;
    passage_id?: (string | null);
};

export type PlanAttempt = {
    item_id: string;
    attempt_id: string;
    status: string;
    overall?: (number | null);
    completeness?: (number | null);
    fluency?: (number | null);
    transcript?: (string | null);
    advice?: (Array<(string)> | null);
    error?: (string | null);
};

export type PlanItem = {
    type: string;
    id: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds: number;
    band?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionUpdate = {
    band?: (string | null);
    text?: (string | null);
    audio_url?: (string | null);
    suggested_seconds?: (number | null);
    order_index?: (number | null);
};

export type RepeatSentence = {
    id?: string;
    passage_id: string;
    order_index: number;
    text: string;
    audio_url?: (string | null);
    suggested_seconds?: number;
};

export type Scenario = {
    id?: string;
    topic: string;
    is_active?: boolean;
};

/**
 * list_scenarios 的响应形状：情景 + 其问法列表。
 */
export type ScenarioOut = {
    id: string;
    topic: string;
    is_active: boolean;
    questions: Array<ScenarioQuestionPublic>;
};

export type ScenarioQuestion = {
    id?: string;
    scenario_id: string;
    band: string;
    order_index?: number;
    text: string;
    audio_url?: (string | null);
    suggested_seconds?: number;
};

export type ScenarioQuestionPublic = {
    id: string;
    band: string;
    text: string;
    audio_url?: (string | null);
    suggested_seconds: number;
};

export type ScenarioUpdate = {
    topic?: (string | null);
    is_active?: (boolean | null);
};

export type StudentJoin = {
    display_name: string;
};

export type StudentPublic = {
    id: string;
    display_name: string;
    suffix?: (string | null);
    current_band: string;
    classroom_id: string;
};

export type TodayPlan = {
    session_id: string;
    classroom_code: string;
    band: string;
    items: Array<PlanItem>;
    attempts: Array<PlanAttempt>;
    questions_exhausted?: boolean;
    gamification?: (GamificationInfo | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrailData = {
    classroom_code: string;
    student_id: string;
    display_name: string;
    suffix?: (string | null);
    sessions: Array<TrailSession>;
    band_change?: (string | null);
};

export type TrailSession = {
    date: string;
    speaking_avg?: (number | null);
    repeat_completeness_avg?: (number | null);
    vocab_cefr?: (string | null);
    attempt_count?: number;
};

export type TtsRequest = {
    text: string;
    voice?: (string | null);
};

export type UnitCreate = {
    order_index?: number;
    title: string;
    topic: string;
    is_active?: boolean;
};

export type UnitPublic = {
    id: string;
    order_index: number;
    title: string;
    topic: string;
    is_active: boolean;
};

export type UnitUpdate = {
    order_index?: (number | null);
    title?: (string | null);
    topic?: (string | null);
    is_active?: (boolean | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WordlistImportResult = {
    imported: number;
    invalid_rows?: Array<(number)>;
};

export type WordlistStats = {
    total: number;
    by_band: {
        [key: string]: (number);
    };
    name?: (string | null);
};

export type AdminListPassagesResponse = (Array<PassageWithSentences>);

export type AdminCreatePassageData = {
    requestBody: PassageCreate;
};

export type AdminCreatePassageResponse = (PassagePublic);

export type AdminUpdatePassageData = {
    passageId: string;
    requestBody: PassageCreate;
};

export type AdminUpdatePassageResponse = (PassagePublic);

export type AdminDeletePassageData = {
    passageId: string;
};

export type AdminDeletePassageResponse = ({
    [key: string]: (string);
});

export type AdminCreateSentenceData = {
    passageId: string;
    requestBody: RepeatSentence;
};

export type AdminCreateSentenceResponse = (RepeatSentence);

export type AdminUpdateSentenceData = {
    requestBody: RepeatSentence;
    sentenceId: string;
};

export type AdminUpdateSentenceResponse = (RepeatSentence);

export type AdminDeleteSentenceData = {
    sentenceId: string;
};

export type AdminDeleteSentenceResponse = ({
    [key: string]: (string);
});

export type AdminListScenariosResponse = (Array<ScenarioOut>);

export type AdminCreateScenarioData = {
    requestBody: Scenario;
};

export type AdminCreateScenarioResponse = (unknown);

export type AdminDeleteScenarioData = {
    scenarioId: string;
};

export type AdminDeleteScenarioResponse = ({
    [key: string]: (string);
});

export type AdminUpdateScenarioData = {
    requestBody: ScenarioUpdate;
    scenarioId: string;
};

export type AdminUpdateScenarioResponse = (unknown);

export type AdminCreateQuestionData = {
    requestBody: ScenarioQuestion;
    scenarioId: string;
};

export type AdminCreateQuestionResponse = (ScenarioQuestionPublic);

export type AdminDeleteQuestionData = {
    questionId: string;
};

export type AdminDeleteQuestionResponse = ({
    [key: string]: (string);
});

export type AdminUpdateQuestionData = {
    questionId: string;
    requestBody: QuestionUpdate;
};

export type AdminUpdateQuestionResponse = (ScenarioQuestionPublic);

export type AdminWordlistStatsResponse = (WordlistStats);

export type AdminImportWordlistCsvData = {
    formData: Body_admin_import_wordlist_csv;
};

export type AdminImportWordlistCsvResponse = (WordlistImportResult);

export type AdminListUnitsResponse = (Array<UnitPublic>);

export type AdminCreateUnitData = {
    requestBody: UnitCreate;
};

export type AdminCreateUnitResponse = (UnitPublic);

export type AdminUpdateUnitData = {
    requestBody: UnitUpdate;
    unitId: string;
};

export type AdminUpdateUnitResponse = (UnitPublic);

export type AdminDeleteUnitData = {
    unitId: string;
};

export type AdminDeleteUnitResponse = ({
    [key: string]: (string);
});

export type AdminListClassroomsResponse = (Array<ClassroomPublic>);

export type AdminDeactivateClassroomData = {
    classroomId: string;
};

export type AdminDeactivateClassroomResponse = ({
    [key: string]: (string);
});

export type AdminUpdateClassroomData = {
    classroomId: string;
    requestBody: ClassroomUpdate;
};

export type AdminUpdateClassroomResponse = (ClassroomPublic);

export type AdminGenerateQuestionsData = {
    requestBody: GenerateRequest;
    scenarioId: string;
};

export type AdminGenerateQuestionsResponse = (Array<DraftQuestionOut>);

export type AdminAutoSplitSentencesData = {
    passageId: string;
    targetCount?: number;
};

export type AdminAutoSplitSentencesResponse = (AutoSplitResult);

export type AdminGenerateStandardAudioData = {
    requestBody: TtsRequest;
};

export type AdminGenerateStandardAudioResponse = (AudioUrlResult);

export type AdminUploadStandardAudioData = {
    formData: Body_admin_upload_standard_audio;
};

export type AdminUploadStandardAudioResponse = (AudioUrlResult);

export type AttemptsCreateAttemptUploadData = {
    formData: Body_attempts_create_attempt_upload;
};

export type AttemptsCreateAttemptUploadResponse = (AttemptPublic);

export type AttemptsReadAttemptData = {
    attemptId: string;
};

export type AttemptsReadAttemptResponse = (AttemptPublic);

export type AttemptsReadAttemptAudioData = {
    attemptId: string;
};

export type AttemptsReadAttemptAudioResponse = (unknown);

export type AudioReadContentAudioData = {
    filename: string;
};

export type AudioReadContentAudioResponse = (unknown);

export type ClassesCreateClassData = {
    requestBody: ClassroomCreate;
};

export type ClassesCreateClassResponse = (ClassroomPublic);

export type ClassesJoinClassData = {
    code: string;
    requestBody: StudentJoin;
};

export type ClassesJoinClassResponse = (StudentPublic);

export type ClassesReadTodayPlanData = {
    code: string;
    studentId: string;
};

export type ClassesReadTodayPlanResponse = (TodayPlan);

export type ClassesReadNextQuestionData = {
    code: string;
    excludeIds?: Array<(string)>;
    studentId: string;
};

export type ClassesReadNextQuestionResponse = (NextQuestion);

export type ClassesReadClassBoardData = {
    code: string;
};

export type ClassesReadClassBoardResponse = (BoardData);

export type ClassesReadStudentTrailData = {
    code: string;
    studentId: string;
};

export type ClassesReadStudentTrailResponse = (TrailData);

export type ClassesReadLearningPathData = {
    code: string;
    studentId: string;
};

export type ClassesReadLearningPathResponse = (LearningPath);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PracticeReadActivePassageResponse = (PassagePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadyCheckResponse = (Message);