"""add practice session mode

Revision ID: 028d9b2ddb30
Revises: 4b4652b870b9
Create Date: 2026-09-26 09:49:24.176111

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '028d9b2ddb30'
down_revision = '4b4652b870b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), server_default='daily', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_session', 'mode')
    # ### end Alembic commands ###
