"""add vocabulary module tables

Revision ID: 0ba1f702626c
Revises: c8d5f2a9e1b4
Create Date: 2026-10-01 18:55:21.893614

背单词模块 P0（设计文档 docs/vocabulary-module-design.md）：
- vocabulary_word / vocabulary_book / vocabulary_book_item：独立词库
  （与口语分析的 wordlist_entry 分离），同库不重复收词、有序
- vocabulary_assignment：发布快照（snapshot_items）+ 版本号；
  vocabulary_assignment_target：发布时固化的目标名单（完成率分母）
- vocabulary_session / vocabulary_answer：作答会话与可审计判分记录
  （首答口径；幂等键唯一；一个学生一个任务一份会话）
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ba1f702626c'
down_revision = 'c8d5f2a9e1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_word',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('headword', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('part_of_speech', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('meaning_zh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('meaning_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('accepted_spellings', sa.JSON(), nullable=True),
    sa.Column('example_en', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_word_headword'), 'vocabulary_word', ['headword'], unique=False)
    op.create_index(op.f('ix_vocabulary_word_status'), 'vocabulary_word', ['status'], unique=False)
    op.create_table('vocabulary_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), server_default='practice', nullable=False),
    sa.Column('prompt_types', sa.JSON(), nullable=True),
    sa.Column('snapshot_items', sa.JSON(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'version_no', name='uq_vocab_assignment_version')
    )
    op.create_index(op.f('ix_vocabulary_assignment_classroom_id'), 'vocabulary_assignment', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_assignment_status'), 'vocabulary_assignment', ['status'], unique=False)
    op.create_table('vocabulary_book',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('classroom_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_book_classroom_id'), 'vocabulary_book', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_book_owner_id'), 'vocabulary_book', ['owner_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_book_scope'), 'vocabulary_book', ['scope'], unique=False)
    op.create_table('vocabulary_assignment_target',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['vocabulary_assignment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_vocab_target_student')
    )
    op.create_index(op.f('ix_vocabulary_assignment_target_assignment_id'), 'vocabulary_assignment_target', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_assignment_target_student_id'), 'vocabulary_assignment_target', ['student_id'], unique=False)
    op.create_table('vocabulary_book_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['vocabulary_book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['vocabulary_word.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'word_id', name='uq_vocab_book_word')
    )
    op.create_index(op.f('ix_vocabulary_book_item_book_id'), 'vocabulary_book_item', ['book_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_book_item_word_id'), 'vocabulary_book_item', ['word_id'], unique=False)
    op.create_table('vocabulary_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=16), server_default='practice', nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), server_default='in_progress', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['vocabulary_assignment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vocab_session_assignment_student', 'vocabulary_session', ['assignment_id', 'student_id'], unique=True, postgresql_where=sa.text('assignment_id IS NOT NULL'))
    op.create_index(op.f('ix_vocabulary_session_assignment_id'), 'vocabulary_session', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_session_classroom_id'), 'vocabulary_session', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_session_student_id'), 'vocabulary_session', ['student_id'], unique=False)
    op.create_table('vocabulary_answer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('answer_raw', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('answer_normalized', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('word_id', sa.Uuid(), nullable=False),
    sa.Column('headword', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('meaning_zh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['vocabulary_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_vocab_answer_idempotency_key'),
    sa.UniqueConstraint('session_id', 'item_index', 'attempt_no', name='uq_vocab_answer_slot')
    )
    op.create_index('ix_vocab_answer_session_item', 'vocabulary_answer', ['session_id', 'item_index'], unique=False)
    op.create_index(op.f('ix_vocabulary_answer_session_id'), 'vocabulary_answer', ['session_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_answer_word_id'), 'vocabulary_answer', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_answer_word_id'), table_name='vocabulary_answer')
    op.drop_index(op.f('ix_vocabulary_answer_session_id'), table_name='vocabulary_answer')
    op.drop_index('ix_vocab_answer_session_item', table_name='vocabulary_answer')
    op.drop_table('vocabulary_answer')
    op.drop_index(op.f('ix_vocabulary_session_student_id'), table_name='vocabulary_session')
    op.drop_index(op.f('ix_vocabulary_session_classroom_id'), table_name='vocabulary_session')
    op.drop_index(op.f('ix_vocabulary_session_assignment_id'), table_name='vocabulary_session')
    op.drop_index('ix_vocab_session_assignment_student', table_name='vocabulary_session', postgresql_where=sa.text('assignment_id IS NOT NULL'))
    op.drop_table('vocabulary_session')
    op.drop_index(op.f('ix_vocabulary_book_item_word_id'), table_name='vocabulary_book_item')
    op.drop_index(op.f('ix_vocabulary_book_item_book_id'), table_name='vocabulary_book_item')
    op.drop_table('vocabulary_book_item')
    op.drop_index(op.f('ix_vocabulary_assignment_target_student_id'), table_name='vocabulary_assignment_target')
    op.drop_index(op.f('ix_vocabulary_assignment_target_assignment_id'), table_name='vocabulary_assignment_target')
    op.drop_table('vocabulary_assignment_target')
    op.drop_index(op.f('ix_vocabulary_book_scope'), table_name='vocabulary_book')
    op.drop_index(op.f('ix_vocabulary_book_owner_id'), table_name='vocabulary_book')
    op.drop_index(op.f('ix_vocabulary_book_classroom_id'), table_name='vocabulary_book')
    op.drop_table('vocabulary_book')
    op.drop_index(op.f('ix_vocabulary_assignment_status'), table_name='vocabulary_assignment')
    op.drop_index(op.f('ix_vocabulary_assignment_classroom_id'), table_name='vocabulary_assignment')
    op.drop_table('vocabulary_assignment')
    op.drop_index(op.f('ix_vocabulary_word_status'), table_name='vocabulary_word')
    op.drop_index(op.f('ix_vocabulary_word_headword'), table_name='vocabulary_word')
    op.drop_table('vocabulary_word')
    # ### end Alembic commands ###
