"""add unique constraint on idempotency_key

Revision ID: 1800e09cea00
Revises: c5f7a9e14b2e
Create Date: 2026-09-27 06:40:32.891729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1800e09cea00'
down_revision = 'c5f7a9e14b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
