"""add content translation fields

Revision ID: 2c7f71022d00
Revises: 028d9b2ddb30
Create Date: 2026-09-26 15:46:41.373157

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c7f71022d00'
down_revision = '028d9b2ddb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passage', sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('repeat_sentence', sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    op.add_column('scenario_question', sa.Column('translation', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_question', 'translation')
    op.drop_column('repeat_sentence', 'translation')
    op.drop_column('passage', 'translation')
    # ### end Alembic commands ###
