"""add gamification fields badge table

Revision ID: 32e2882c6d76
Revises: 13d7823e5e93
Create Date: 2026-09-26 08:03:21.085632

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32e2882c6d76'
down_revision = '13d7823e5e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('badge_key', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_badge_badge_key'), 'student_badge', ['badge_key'], unique=False)
    op.create_index(op.f('ix_student_badge_student_id'), 'student_badge', ['student_id'], unique=False)
    op.add_column('practice_session', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('student', sa.Column('streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('student', sa.Column('last_practice_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'last_practice_date')
    op.drop_column('student', 'streak_days')
    op.drop_column('student', 'xp')
    op.drop_column('practice_session', 'stars')
    op.drop_index(op.f('ix_student_badge_student_id'), table_name='student_badge')
    op.drop_index(op.f('ix_student_badge_badge_key'), table_name='student_badge')
    op.drop_table('student_badge')
    # ### end Alembic commands ###
