"""add sentence frames and student favorites

句型推荐与收藏（PR B）：sentence_frame 按共享五级 + 表达用途分类的可替换
句型（exam_kind 可空=通用）；student_frame_favorite 学生按单条收藏
（挂课堂档案，跨设备可见）。推荐注入仅在练习展示层，不进作答快照。
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3c1f7a87917b'
down_revision = '7b5db027aea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_frame',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=False),
    sa.Column('exam_kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text_zh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_frame_level'), 'sentence_frame', ['level'], unique=False)
    op.create_index(op.f('ix_sentence_frame_purpose'), 'sentence_frame', ['purpose'], unique=False)
    op.create_index(op.f('ix_sentence_frame_status'), 'sentence_frame', ['status'], unique=False)
    op.create_table('student_frame_favorite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('frame_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['sentence_frame.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'frame_id', name='uq_student_frame_favorite')
    )
    op.create_index(op.f('ix_student_frame_favorite_frame_id'), 'student_frame_favorite', ['frame_id'], unique=False)
    op.create_index(op.f('ix_student_frame_favorite_student_id'), 'student_frame_favorite', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_frame_favorite_student_id'), table_name='student_frame_favorite')
    op.drop_index(op.f('ix_student_frame_favorite_frame_id'), table_name='student_frame_favorite')
    op.drop_table('student_frame_favorite')
    op.drop_index(op.f('ix_sentence_frame_status'), table_name='sentence_frame')
    op.drop_index(op.f('ix_sentence_frame_purpose'), table_name='sentence_frame')
    op.drop_index(op.f('ix_sentence_frame_level'), table_name='sentence_frame')
    op.drop_table('sentence_frame')
    # ### end Alembic commands ###
