"""add attempt rubric

Revision ID: 44d17fa1208e
Revises: 9da4f3c31da4
Create Date: 2026-09-26 07:04:02.517323

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44d17fa1208e'
down_revision = '9da4f3c31da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempt', sa.Column('rubric', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'rubric')
    # ### end Alembic commands ###
