"""add classroom current unit assignment

Revision ID: 4b4652b870b9
Revises: bdd8ff69d22b
Create Date: 2026-09-26 09:17:36.997702

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4b4652b870b9'
down_revision = 'bdd8ff69d22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom', sa.Column('current_unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'classroom', 'unit', ['current_unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classroom', 'current_unit_id')
    # ### end Alembic commands ###
