"""add classroom student session scenario tables

Revision ID: 4df0a1549bb9
Revises: 7da1c4d8076f
Create Date: 2026-09-26 05:53:56.703191

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4df0a1549bb9'
down_revision = '7da1c4d8076f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_code'), 'classroom', ['code'], unique=True)
    op.create_table('scenario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_topic'), 'scenario', ['topic'], unique=True)
    op.create_table('repeat_sentence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('suggested_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passage_id'], ['passage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('suggested_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_question_band'), 'scenario_question', ['band'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('suffix', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=True),
    sa.Column('current_band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('question_band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attempt', sa.Column('item_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False))
    op.add_column('attempt', sa.Column('item_id', sa.Uuid(), nullable=False))
    op.add_column('attempt', sa.Column('student_id', sa.Uuid(), nullable=True))
    op.add_column('attempt', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_attempt_item_id'), 'attempt', ['item_id'], unique=False)
    op.create_index(op.f('ix_attempt_item_type'), 'attempt', ['item_type'], unique=False)
    op.drop_constraint(op.f('attempt_passage_id_fkey'), 'attempt', type_='foreignkey')
    op.create_foreign_key(None, 'attempt', 'student', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attempt', 'practice_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attempt', 'passage_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 说明：session_id/student_id 列的 FK 随 drop_column 一并删除（Postgres 行为），
    # 自动生成的 drop_constraint(None) 不合法，已移除。
    op.add_column('attempt', sa.Column('passage_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('attempt_passage_id_fkey'), 'attempt', 'passage', ['passage_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attempt_item_type'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_item_id'), table_name='attempt')
    op.drop_column('attempt', 'session_id')
    op.drop_column('attempt', 'student_id')
    op.drop_column('attempt', 'item_id')
    op.drop_column('attempt', 'item_type')
    op.drop_table('practice_session')
    op.drop_table('student')
    op.drop_index(op.f('ix_scenario_question_band'), table_name='scenario_question')
    op.drop_table('scenario_question')
    op.drop_table('repeat_sentence')
    op.drop_index(op.f('ix_scenario_topic'), table_name='scenario')
    op.drop_table('scenario')
    op.drop_index(op.f('ix_classroom_code'), table_name='classroom')
    op.drop_table('classroom')
    # ### end Alembic commands ###
