"""add exchanged item ids to practice session

分级题型训练换题授权（PR A 七审修复）：学生点「换一题」返回的计划外
题目，其**完整快照**（发布时刻内容，含考试字段）存入
practice_session.exchanged_items；提交接口据此放行并返回同一份快照——
老师此后改题干/话题卡或删题，均不影响学生已看到的题目与评分依据。
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7b5db027aea6'
down_revision = 'b3da398beb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('exchanged_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_session', 'exchanged_items')
    # ### end Alembic commands ###
