"""add exchanged item ids to practice session

分级题型训练换题授权（PR A 六审修复）：学生点「换一题」返回的计划外题目
id 记入 practice_session.exchanged_item_ids，提交接口据此放行并从题库行
构建 item_snapshot（评分与结果页读同一份内容）。
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7b5db027aea6'
down_revision = 'b3da398beb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_session', sa.Column('exchanged_item_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_session', 'exchanged_item_ids')
    # ### end Alembic commands ###
