"""add passage and attempt tables

Revision ID: 7da1c4d8076f
Revises: 0001
Create Date: 2026-09-25 23:25:53.344372

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7da1c4d8076f'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cefr_band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('suggested_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passage_slug'), 'passage', ['slug'], unique=True)
    op.create_table('attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('passage_id', sa.Uuid(), nullable=False),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('audio_mime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.Column('fluency', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('advice', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passage_id'], ['passage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_status'), 'attempt', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_status'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_passage_slug'), table_name='passage')
    op.drop_table('passage')
    # ### end Alembic commands ###
