"""add wordlist entry and attempt vocab

Revision ID: 9da4f3c31da4
Revises: 4df0a1549bb9
Create Date: 2026-09-26 06:49:52.063686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9da4f3c31da4'
down_revision = '4df0a1549bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('band', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordlist_entry_band'), 'wordlist_entry', ['band'], unique=False)
    op.create_index(op.f('ix_wordlist_entry_lemma'), 'wordlist_entry', ['lemma'], unique=True)
    op.add_column('attempt', sa.Column('vocab', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt', 'vocab')
    op.drop_index(op.f('ix_wordlist_entry_lemma'), table_name='wordlist_entry')
    op.drop_index(op.f('ix_wordlist_entry_band'), table_name='wordlist_entry')
    op.drop_table('wordlist_entry')
    # ### end Alembic commands ###
