"""add five level vocab entry table

五级词库（口语与背单词共用分级数据源，docs/five-level-vocab-quality-report.md）：
- vocab_level_entry：KET/PET/学术/四级/雅思&托福 固定顺序，实际难度取最早一级
- 同形异义按 (headword, level, sense_no) 各占一行；来源标签存 sources JSON
- 与 wordlist_entry（A2/B1/B2）完全独立，历史结果不漂移

Revision ID: b28dcb2c54ae
Revises: 0ba1f702626c
Create Date: 2026-10-03 06:21:28.601907

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b28dcb2c54ae'
down_revision = '0ba1f702626c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_level_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('headword', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('sense_no', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('meaning_zh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_phrase', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headword', 'level', 'sense_no', name='uq_vocab_level_sense')
    )
    op.create_index(op.f('ix_vocab_level_entry_headword'), 'vocab_level_entry', ['headword'], unique=False)
    op.create_index('ix_vocab_level_level_headword', 'vocab_level_entry', ['level', 'headword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vocab_level_level_headword', table_name='vocab_level_entry')
    op.drop_index(op.f('ix_vocab_level_entry_headword'), table_name='vocab_level_entry')
    op.drop_table('vocab_level_entry')
    # ### end Alembic commands ###
