"""add exam task fields to repeat and question

分级题型训练（PR A：题库与练习流程）——复用既有两表，可空列逐条附加：
- repeat_sentence.exam_kind / exam_level：TOEFL Listen and Repeat 等复述类
- scenario_question.exam_kind / exam_level：Take an Interview、IELTS Part 1/2/3
- scenario_question.cue_card_bullets / prep_seconds：Part 2 话题卡要点与准备时间
旧数据两列为 NULL，含义与流程完全不变（不重新解释历史题目/作答）。
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3da398beb03'
down_revision = 'b28dcb2c54ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repeat_sentence', sa.Column('exam_kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True))
    op.add_column('repeat_sentence', sa.Column('exam_level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.add_column('scenario_question', sa.Column('exam_kind', sqlmodel.sql.sqltypes.AutoString(length=24), nullable=True))
    op.add_column('scenario_question', sa.Column('exam_level', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.add_column('scenario_question', sa.Column('cue_card_bullets', sa.JSON(), nullable=True))
    op.add_column('scenario_question', sa.Column('prep_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_question', 'prep_seconds')
    op.drop_column('scenario_question', 'cue_card_bullets')
    op.drop_column('scenario_question', 'exam_level')
    op.drop_column('scenario_question', 'exam_kind')
    op.drop_column('repeat_sentence', 'exam_level')
    op.drop_column('repeat_sentence', 'exam_kind')
    # ### end Alembic commands ###
