"""add unit table and path fields

Revision ID: bdd8ff69d22b
Revises: 32e2882c6d76
Create Date: 2026-09-26 08:14:56.559301

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bdd8ff69d22b'
down_revision = '32e2882c6d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_order_index'), 'unit', ['order_index'], unique=False)
    op.add_column('classroom', sa.Column('unlock_all', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('passage', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'passage', 'unit', ['unit_id'], ['id'], ondelete='SET NULL')
    op.add_column('practice_session', sa.Column('passage_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'practice_session', 'passage', ['passage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_session', 'passage_id')
    op.drop_column('passage', 'unit_id')  # FK 随列删除
    op.drop_column('classroom', 'unlock_all')
    op.drop_index(op.f('ix_unit_order_index'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
