"""add student unique constraints for display_name

Revision ID: eec39eea422c
Revises: 1800e09cea00
Create Date: 2026-09-27 06:43:40.134209

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eec39eea422c'
down_revision = '1800e09cea00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
