"""vocab session round_no

Revision ID: ff23287ceb31
Revises: 3c1f7a87917b
Create Date: 2026-10-05 08:16:20.278454

回退限制：downgrade 重建旧唯一索引 (assignment_id, student_id)——若已存在
多轮数据（同学生同任务 >1 轮，round_no>1），旧索引会因重复而创建失败。
多轮记录是学生真实练习历史，不提供「删复习轮换回滚」的有损路径；
需要回退时先确认无多轮数据，或接受保留 vocabulary_session 表
（不降级该表）的手工方案。
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ff23287ceb31"
down_revision = "3c1f7a87917b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vocabulary_session",
        sa.Column("round_no", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_index(
        op.f("ix_vocab_session_assignment_student"),
        table_name="vocabulary_session",
        postgresql_where="(assignment_id IS NOT NULL)",
    )
    op.create_index(
        "ix_vocab_session_assignment_student_round",
        "vocabulary_session",
        ["assignment_id", "student_id", "round_no"],
        unique=True,
        postgresql_where=sa.text("assignment_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # 已有多轮数据时，旧唯一索引无法重建（重复键）；让失败信息直接暴露，
    # 不做静默删数。见模块 docstring 的回退限制说明。
    op.drop_index(
        "ix_vocab_session_assignment_student_round",
        table_name="vocabulary_session",
        postgresql_where=sa.text("assignment_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_vocab_session_assignment_student"),
        "vocabulary_session",
        ["assignment_id", "student_id"],
        unique=True,
        postgresql_where="(assignment_id IS NOT NULL)",
    )
    op.drop_column("vocabulary_session", "round_no")
    # ### end Alembic commands ###
