"""vocab session round_no

Revision ID: ff23287ceb31
Revises: 3c1f7a87917b
Create Date: 2026-10-05 08:16:20.278454

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ff23287ceb31"
down_revision = "3c1f7a87917b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vocabulary_session",
        sa.Column("round_no", sa.Integer(), server_default="1", nullable=False),
    )
    op.drop_index(
        op.f("ix_vocab_session_assignment_student"),
        table_name="vocabulary_session",
        postgresql_where="(assignment_id IS NOT NULL)",
    )
    op.create_index(
        "ix_vocab_session_assignment_student_round",
        "vocabulary_session",
        ["assignment_id", "student_id", "round_no"],
        unique=True,
        postgresql_where=sa.text("assignment_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_vocab_session_assignment_student_round",
        table_name="vocabulary_session",
        postgresql_where=sa.text("assignment_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_vocab_session_assignment_student"),
        "vocabulary_session",
        ["assignment_id", "student_id"],
        unique=True,
        postgresql_where="(assignment_id IS NOT NULL)",
    )
    op.drop_column("vocabulary_session", "round_no")
    # ### end Alembic commands ###
