/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutClassroomsRouteImport } from './routes/_layout/classrooms'
import { Route as LayoutCreateRouteImport } from './routes/_layout/create'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as ClassroomCodeRouteImport } from './routes/classroom.$code'
import { Route as ExploreCodeRouteImport } from './routes/explore.$code'
import { Route as HelpCodeRouteImport } from './routes/help.$code'
import { Route as HomeCodeRouteImport } from './routes/home.$code'
import { Route as JCodeRouteImport } from './routes/j.$code'
import { Route as MeCodeRouteImport } from './routes/me.$code'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as TCodeRouteImport } from './routes/t.$code'
import { Route as VocabCodeRouteImport } from './routes/vocab.$code'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutAdminClassroomsRouteImport } from './routes/_layout/admin.classrooms'
import { Route as LayoutAdminPassagesRouteImport } from './routes/_layout/admin.passages'
import { Route as LayoutAdminQuestionsRouteImport } from './routes/_layout/admin.questions'
import { Route as LayoutAdminScenariosRouteImport } from './routes/_layout/admin.scenarios'
import { Route as LayoutAdminSentenceframesRouteImport } from './routes/_layout/admin.sentenceframes'
import { Route as LayoutAdminUnitsRouteImport } from './routes/_layout/admin.units'
import { Route as LayoutAdminVocabbooksRouteImport } from './routes/_layout/admin.vocabbooks'
import { Route as LayoutAdminVocablevelsRouteImport } from './routes/_layout/admin.vocablevels'
import { Route as LayoutAdminWordlistRouteImport } from './routes/_layout/admin.wordlist'
import { Route as PCodeIndexRouteImport } from './routes/p.$code.index'
import { Route as PCodeResultRouteImport } from './routes/p.$code.result'
import { Route as TCodeIndexRouteImport } from './routes/t.$code.index'
import { Route as TCodeVocabRouteImport } from './routes/t.$code.vocab'
import { Route as VocabCodeIndexRouteImport } from './routes/vocab.$code.index'
import { Route as VocabCodePracticeRouteImport } from './routes/vocab.$code.practice'
import { Route as TCodeSStudentIdRouteImport } from './routes/t.$code.s.$studentId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClassroomsRoute = LayoutClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateRoute = LayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const ClassroomCodeRoute = ClassroomCodeRouteImport.update({
  id: '/classroom/$code',
  path: '/classroom/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreCodeRoute = ExploreCodeRouteImport.update({
  id: '/explore/$code',
  path: '/explore/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCodeRoute = HelpCodeRouteImport.update({
  id: '/help/$code',
  path: '/help/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCodeRoute = HomeCodeRouteImport.update({
  id: '/home/$code',
  path: '/home/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JCodeRoute = JCodeRouteImport.update({
  id: '/j/$code',
  path: '/j/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MeCodeRoute = MeCodeRouteImport.update({
  id: '/me/$code',
  path: '/me/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabCodeRoute = VocabCodeRouteImport.update({
  id: '/vocab/$code',
  path: '/vocab/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminClassroomsRoute = LayoutAdminClassroomsRouteImport.update({
  id: '/classrooms',
  path: '/classrooms',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPassagesRoute = LayoutAdminPassagesRouteImport.update({
  id: '/passages',
  path: '/passages',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminQuestionsRoute = LayoutAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminScenariosRoute = LayoutAdminScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSentenceframesRoute =
  LayoutAdminSentenceframesRouteImport.update({
    id: '/sentenceframes',
    path: '/sentenceframes',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminUnitsRoute = LayoutAdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminVocabbooksRoute = LayoutAdminVocabbooksRouteImport.update({
  id: '/vocabbooks',
  path: '/vocabbooks',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminVocablevelsRoute = LayoutAdminVocablevelsRouteImport.update({
  id: '/vocablevels',
  path: '/vocablevels',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminWordlistRoute = LayoutAdminWordlistRouteImport.update({
  id: '/wordlist',
  path: '/wordlist',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const PCodeIndexRoute = PCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PCodeRoute,
} as any)
const PCodeResultRoute = PCodeResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PCodeRoute,
} as any)
const TCodeIndexRoute = TCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TCodeRoute,
} as any)
const TCodeVocabRoute = TCodeVocabRouteImport.update({
  id: '/vocab',
  path: '/vocab',
  getParentRoute: () => TCodeRoute,
} as any)
const VocabCodeIndexRoute = VocabCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VocabCodeRoute,
} as any)
const VocabCodePracticeRoute = VocabCodePracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => VocabCodeRoute,
} as any)
const TCodeSStudentIdRoute = TCodeSStudentIdRouteImport.update({
  id: '/s/$studentId',
  path: '/s/$studentId',
  getParentRoute: () => TCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/classrooms': typeof LayoutClassroomsRoute
  '/create': typeof LayoutCreateRoute
  '/settings': typeof LayoutSettingsRoute
  '/classroom/$code': typeof ClassroomCodeRoute
  '/explore/$code': typeof ExploreCodeRoute
  '/help/$code': typeof HelpCodeRoute
  '/home/$code': typeof HomeCodeRoute
  '/j/$code': typeof JCodeRoute
  '/me/$code': typeof MeCodeRoute
  '/p/$code': typeof PCodeRouteWithChildren
  '/t/$code': typeof TCodeRouteWithChildren
  '/vocab/$code': typeof VocabCodeRouteWithChildren
  '/admin/classrooms': typeof LayoutAdminClassroomsRoute
  '/admin/passages': typeof LayoutAdminPassagesRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/admin/scenarios': typeof LayoutAdminScenariosRoute
  '/admin/sentenceframes': typeof LayoutAdminSentenceframesRoute
  '/admin/units': typeof LayoutAdminUnitsRoute
  '/admin/vocabbooks': typeof LayoutAdminVocabbooksRoute
  '/admin/vocablevels': typeof LayoutAdminVocablevelsRoute
  '/admin/wordlist': typeof LayoutAdminWordlistRoute
  '/p/$code/result': typeof PCodeResultRoute
  '/t/$code/vocab': typeof TCodeVocabRoute
  '/vocab/$code/practice': typeof VocabCodePracticeRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/p/$code/': typeof PCodeIndexRoute
  '/t/$code/': typeof TCodeIndexRoute
  '/vocab/$code/': typeof VocabCodeIndexRoute
  '/t/$code/s/$studentId': typeof TCodeSStudentIdRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/classrooms': typeof LayoutClassroomsRoute
  '/create': typeof LayoutCreateRoute
  '/settings': typeof LayoutSettingsRoute
  '/classroom/$code': typeof ClassroomCodeRoute
  '/explore/$code': typeof ExploreCodeRoute
  '/help/$code': typeof HelpCodeRoute
  '/home/$code': typeof HomeCodeRoute
  '/j/$code': typeof JCodeRoute
  '/me/$code': typeof MeCodeRoute
  '/': typeof LayoutIndexRoute
  '/admin/classrooms': typeof LayoutAdminClassroomsRoute
  '/admin/passages': typeof LayoutAdminPassagesRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/admin/scenarios': typeof LayoutAdminScenariosRoute
  '/admin/sentenceframes': typeof LayoutAdminSentenceframesRoute
  '/admin/units': typeof LayoutAdminUnitsRoute
  '/admin/vocabbooks': typeof LayoutAdminVocabbooksRoute
  '/admin/vocablevels': typeof LayoutAdminVocablevelsRoute
  '/admin/wordlist': typeof LayoutAdminWordlistRoute
  '/p/$code/result': typeof PCodeResultRoute
  '/t/$code/vocab': typeof TCodeVocabRoute
  '/vocab/$code/practice': typeof VocabCodePracticeRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/p/$code': typeof PCodeIndexRoute
  '/t/$code': typeof TCodeIndexRoute
  '/vocab/$code': typeof VocabCodeIndexRoute
  '/t/$code/s/$studentId': typeof TCodeSStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/classrooms': typeof LayoutClassroomsRoute
  '/_layout/create': typeof LayoutCreateRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/classroom/$code': typeof ClassroomCodeRoute
  '/explore/$code': typeof ExploreCodeRoute
  '/help/$code': typeof HelpCodeRoute
  '/home/$code': typeof HomeCodeRoute
  '/j/$code': typeof JCodeRoute
  '/me/$code': typeof MeCodeRoute
  '/p/$code': typeof PCodeRouteWithChildren
  '/t/$code': typeof TCodeRouteWithChildren
  '/vocab/$code': typeof VocabCodeRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/classrooms': typeof LayoutAdminClassroomsRoute
  '/_layout/admin/passages': typeof LayoutAdminPassagesRoute
  '/_layout/admin/questions': typeof LayoutAdminQuestionsRoute
  '/_layout/admin/scenarios': typeof LayoutAdminScenariosRoute
  '/_layout/admin/sentenceframes': typeof LayoutAdminSentenceframesRoute
  '/_layout/admin/units': typeof LayoutAdminUnitsRoute
  '/_layout/admin/vocabbooks': typeof LayoutAdminVocabbooksRoute
  '/_layout/admin/vocablevels': typeof LayoutAdminVocablevelsRoute
  '/_layout/admin/wordlist': typeof LayoutAdminWordlistRoute
  '/p/$code/result': typeof PCodeResultRoute
  '/t/$code/vocab': typeof TCodeVocabRoute
  '/vocab/$code/practice': typeof VocabCodePracticeRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/p/$code/': typeof PCodeIndexRoute
  '/t/$code/': typeof TCodeIndexRoute
  '/vocab/$code/': typeof VocabCodeIndexRoute
  '/t/$code/s/$studentId': typeof TCodeSStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/join'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/classrooms'
    | '/create'
    | '/settings'
    | '/classroom/$code'
    | '/explore/$code'
    | '/help/$code'
    | '/home/$code'
    | '/j/$code'
    | '/me/$code'
    | '/p/$code'
    | '/t/$code'
    | '/vocab/$code'
    | '/admin/classrooms'
    | '/admin/passages'
    | '/admin/questions'
    | '/admin/scenarios'
    | '/admin/sentenceframes'
    | '/admin/units'
    | '/admin/vocabbooks'
    | '/admin/vocablevels'
    | '/admin/wordlist'
    | '/p/$code/result'
    | '/t/$code/vocab'
    | '/vocab/$code/practice'
    | '/admin/'
    | '/p/$code/'
    | '/t/$code/'
    | '/vocab/$code/'
    | '/t/$code/s/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/join'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/classrooms'
    | '/create'
    | '/settings'
    | '/classroom/$code'
    | '/explore/$code'
    | '/help/$code'
    | '/home/$code'
    | '/j/$code'
    | '/me/$code'
    | '/'
    | '/admin/classrooms'
    | '/admin/passages'
    | '/admin/questions'
    | '/admin/scenarios'
    | '/admin/sentenceframes'
    | '/admin/units'
    | '/admin/vocabbooks'
    | '/admin/vocablevels'
    | '/admin/wordlist'
    | '/p/$code/result'
    | '/t/$code/vocab'
    | '/vocab/$code/practice'
    | '/admin'
    | '/p/$code'
    | '/t/$code'
    | '/vocab/$code'
    | '/t/$code/s/$studentId'
  id:
    | '__root__'
    | '/_layout'
    | '/change-password'
    | '/join'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/classrooms'
    | '/_layout/create'
    | '/_layout/settings'
    | '/classroom/$code'
    | '/explore/$code'
    | '/help/$code'
    | '/home/$code'
    | '/j/$code'
    | '/me/$code'
    | '/p/$code'
    | '/t/$code'
    | '/vocab/$code'
    | '/_layout/'
    | '/_layout/admin/classrooms'
    | '/_layout/admin/passages'
    | '/_layout/admin/questions'
    | '/_layout/admin/scenarios'
    | '/_layout/admin/sentenceframes'
    | '/_layout/admin/units'
    | '/_layout/admin/vocabbooks'
    | '/_layout/admin/vocablevels'
    | '/_layout/admin/wordlist'
    | '/p/$code/result'
    | '/t/$code/vocab'
    | '/vocab/$code/practice'
    | '/_layout/admin/'
    | '/p/$code/'
    | '/t/$code/'
    | '/vocab/$code/'
    | '/t/$code/s/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ClassroomCodeRoute: typeof ClassroomCodeRoute
  ExploreCodeRoute: typeof ExploreCodeRoute
  HelpCodeRoute: typeof HelpCodeRoute
  HomeCodeRoute: typeof HomeCodeRoute
  JCodeRoute: typeof JCodeRoute
  MeCodeRoute: typeof MeCodeRoute
  PCodeRoute: typeof PCodeRouteWithChildren
  TCodeRoute: typeof TCodeRouteWithChildren
  VocabCodeRoute: typeof VocabCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/classrooms': {
      id: '/_layout/classrooms'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof LayoutClassroomsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create': {
      id: '/_layout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/classroom/$code': {
      id: '/classroom/$code'
      path: '/classroom/$code'
      fullPath: '/classroom/$code'
      preLoaderRoute: typeof ClassroomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$code': {
      id: '/explore/$code'
      path: '/explore/$code'
      fullPath: '/explore/$code'
      preLoaderRoute: typeof ExploreCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$code': {
      id: '/help/$code'
      path: '/help/$code'
      fullPath: '/help/$code'
      preLoaderRoute: typeof HelpCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$code': {
      id: '/home/$code'
      path: '/home/$code'
      fullPath: '/home/$code'
      preLoaderRoute: typeof HomeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/j/$code': {
      id: '/j/$code'
      path: '/j/$code'
      fullPath: '/j/$code'
      preLoaderRoute: typeof JCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/$code': {
      id: '/me/$code'
      path: '/me/$code'
      fullPath: '/me/$code'
      preLoaderRoute: typeof MeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/$code': {
      id: '/vocab/$code'
      path: '/vocab/$code'
      fullPath: '/vocab/$code'
      preLoaderRoute: typeof VocabCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/classrooms': {
      id: '/_layout/admin/classrooms'
      path: '/classrooms'
      fullPath: '/admin/classrooms'
      preLoaderRoute: typeof LayoutAdminClassroomsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/passages': {
      id: '/_layout/admin/passages'
      path: '/passages'
      fullPath: '/admin/passages'
      preLoaderRoute: typeof LayoutAdminPassagesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/questions': {
      id: '/_layout/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof LayoutAdminQuestionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/scenarios': {
      id: '/_layout/admin/scenarios'
      path: '/scenarios'
      fullPath: '/admin/scenarios'
      preLoaderRoute: typeof LayoutAdminScenariosRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/sentenceframes': {
      id: '/_layout/admin/sentenceframes'
      path: '/sentenceframes'
      fullPath: '/admin/sentenceframes'
      preLoaderRoute: typeof LayoutAdminSentenceframesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/units': {
      id: '/_layout/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof LayoutAdminUnitsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/vocabbooks': {
      id: '/_layout/admin/vocabbooks'
      path: '/vocabbooks'
      fullPath: '/admin/vocabbooks'
      preLoaderRoute: typeof LayoutAdminVocabbooksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/vocablevels': {
      id: '/_layout/admin/vocablevels'
      path: '/vocablevels'
      fullPath: '/admin/vocablevels'
      preLoaderRoute: typeof LayoutAdminVocablevelsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/wordlist': {
      id: '/_layout/admin/wordlist'
      path: '/wordlist'
      fullPath: '/admin/wordlist'
      preLoaderRoute: typeof LayoutAdminWordlistRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/p/$code/': {
      id: '/p/$code/'
      path: '/'
      fullPath: '/p/$code/'
      preLoaderRoute: typeof PCodeIndexRouteImport
      parentRoute: typeof PCodeRoute
    }
    '/p/$code/result': {
      id: '/p/$code/result'
      path: '/result'
      fullPath: '/p/$code/result'
      preLoaderRoute: typeof PCodeResultRouteImport
      parentRoute: typeof PCodeRoute
    }
    '/t/$code/': {
      id: '/t/$code/'
      path: '/'
      fullPath: '/t/$code/'
      preLoaderRoute: typeof TCodeIndexRouteImport
      parentRoute: typeof TCodeRoute
    }
    '/t/$code/vocab': {
      id: '/t/$code/vocab'
      path: '/vocab'
      fullPath: '/t/$code/vocab'
      preLoaderRoute: typeof TCodeVocabRouteImport
      parentRoute: typeof TCodeRoute
    }
    '/vocab/$code/': {
      id: '/vocab/$code/'
      path: '/'
      fullPath: '/vocab/$code/'
      preLoaderRoute: typeof VocabCodeIndexRouteImport
      parentRoute: typeof VocabCodeRoute
    }
    '/vocab/$code/practice': {
      id: '/vocab/$code/practice'
      path: '/practice'
      fullPath: '/vocab/$code/practice'
      preLoaderRoute: typeof VocabCodePracticeRouteImport
      parentRoute: typeof VocabCodeRoute
    }
    '/t/$code/s/$studentId': {
      id: '/t/$code/s/$studentId'
      path: '/s/$studentId'
      fullPath: '/t/$code/s/$studentId'
      preLoaderRoute: typeof TCodeSStudentIdRouteImport
      parentRoute: typeof TCodeRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminClassroomsRoute: typeof LayoutAdminClassroomsRoute
  LayoutAdminPassagesRoute: typeof LayoutAdminPassagesRoute
  LayoutAdminQuestionsRoute: typeof LayoutAdminQuestionsRoute
  LayoutAdminScenariosRoute: typeof LayoutAdminScenariosRoute
  LayoutAdminSentenceframesRoute: typeof LayoutAdminSentenceframesRoute
  LayoutAdminUnitsRoute: typeof LayoutAdminUnitsRoute
  LayoutAdminVocabbooksRoute: typeof LayoutAdminVocabbooksRoute
  LayoutAdminVocablevelsRoute: typeof LayoutAdminVocablevelsRoute
  LayoutAdminWordlistRoute: typeof LayoutAdminWordlistRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminClassroomsRoute: LayoutAdminClassroomsRoute,
  LayoutAdminPassagesRoute: LayoutAdminPassagesRoute,
  LayoutAdminQuestionsRoute: LayoutAdminQuestionsRoute,
  LayoutAdminScenariosRoute: LayoutAdminScenariosRoute,
  LayoutAdminSentenceframesRoute: LayoutAdminSentenceframesRoute,
  LayoutAdminUnitsRoute: LayoutAdminUnitsRoute,
  LayoutAdminVocabbooksRoute: LayoutAdminVocabbooksRoute,
  LayoutAdminVocablevelsRoute: LayoutAdminVocablevelsRoute,
  LayoutAdminWordlistRoute: LayoutAdminWordlistRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutClassroomsRoute: typeof LayoutClassroomsRoute
  LayoutCreateRoute: typeof LayoutCreateRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutClassroomsRoute: LayoutClassroomsRoute,
  LayoutCreateRoute: LayoutCreateRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PCodeRouteChildren {
  PCodeResultRoute: typeof PCodeResultRoute
  PCodeIndexRoute: typeof PCodeIndexRoute
}

const PCodeRouteChildren: PCodeRouteChildren = {
  PCodeResultRoute: PCodeResultRoute,
  PCodeIndexRoute: PCodeIndexRoute,
}

const PCodeRouteWithChildren = PCodeRoute._addFileChildren(PCodeRouteChildren)

interface TCodeRouteChildren {
  TCodeVocabRoute: typeof TCodeVocabRoute
  TCodeIndexRoute: typeof TCodeIndexRoute
  TCodeSStudentIdRoute: typeof TCodeSStudentIdRoute
}

const TCodeRouteChildren: TCodeRouteChildren = {
  TCodeVocabRoute: TCodeVocabRoute,
  TCodeIndexRoute: TCodeIndexRoute,
  TCodeSStudentIdRoute: TCodeSStudentIdRoute,
}

const TCodeRouteWithChildren = TCodeRoute._addFileChildren(TCodeRouteChildren)

interface VocabCodeRouteChildren {
  VocabCodePracticeRoute: typeof VocabCodePracticeRoute
  VocabCodeIndexRoute: typeof VocabCodeIndexRoute
}

const VocabCodeRouteChildren: VocabCodeRouteChildren = {
  VocabCodePracticeRoute: VocabCodePracticeRoute,
  VocabCodeIndexRoute: VocabCodeIndexRoute,
}

const VocabCodeRouteWithChildren = VocabCodeRoute._addFileChildren(
  VocabCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ClassroomCodeRoute: ClassroomCodeRoute,
  ExploreCodeRoute: ExploreCodeRoute,
  HelpCodeRoute: HelpCodeRoute,
  HomeCodeRoute: HomeCodeRoute,
  JCodeRoute: JCodeRoute,
  MeCodeRoute: MeCodeRoute,
  PCodeRoute: PCodeRouteWithChildren,
  TCodeRoute: TCodeRouteWithChildren,
  VocabCodeRoute: VocabCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
