/**
 * 全站术语单一事实源（2026-09 术语统一；2026-09-30 起双语化）。
 *
 * 面向用户的新文案一律从这里取词，避免同一概念再次出现多种叫法。
 * 所有值是 BiString：组件里用 useI18n().t(TERMS.xxx) 取当前语言。
 * 人读版本（含取舍原因）见仓库 CLAUDE.md「术语表」章节。
 */
import type { BiString } from "./bi.ts"

export const TERMS = {
  /** Unit：课堂指派与学生自主练习的基本单位 */
  unit: { zh: "单元", en: "Unit" },
  /** Unit.topic：单元的主题（如「宠物」） */
  topic: { zh: "主题", en: "Topic" },
  /** Passage：朗读/复述用的英文材料 */
  passage: { zh: "篇目", en: "Passage" },
  /** 三种题型（全端统一名称） */
  typeReading: { zh: "文章朗读", en: "Read Aloud" },
  typeRepeat: { zh: "听句复述", en: "Listen & Repeat" },
  typeQa: { zh: "情景问答", en: "Scenario Q&A" },
  /** 学生端每日练习入口（与导航一致） */
  todayPractice: { zh: "今日练习", en: "Today's Practice" },
  /** 老师未发布统一内容时，学生按单元顺序自行练习 */
  selfPractice: { zh: "自主练习", en: "Self Practice" },
  /** 老师把单元下发给全班的动作（教师端按钮用「发布」） */
  publish: { zh: "发布", en: "Publish" },
  /** 词汇学习模块（学生端导航与页面标题） */
  vocabLearning: { zh: "词汇学习", en: "Vocabulary" },
  /** 词汇任务（教师发布给全班的单词练习） */
  vocabTask: { zh: "词汇任务", en: "Vocabulary Task" },
  /** 词库（教师/管理端维护的单词集合） */
  vocabBook: { zh: "词库", en: "Word Book" },
  /** 错词本（学生首答判错的词自动归集） */
  wrongWords: { zh: "错词本", en: "Wrong Words" },
  /** 看义拼词（出题方式） */
  promptMeaning: { zh: "看义拼词", en: "Spell from Meaning" },
  /** 听音拼词（出题方式） */
  promptAudio: { zh: "听音拼词", en: "Spell from Audio" },
  /** 系统给学生的分数口径：不是考试成绩 */
  score: { zh: "参考分", en: "Reference Score" },
  /** 学生成长页（导航与页面标题一致） */
  growthPage: { zh: "我的成长", en: "My Growth" },
  /** 教师端查看学生历史曲线的页面 */
  trailPage: { zh: "进步轨迹", en: "Progress Trail" },
} as const satisfies Record<string, BiString>

/** 激励规则解释（触点小字 / Tooltip / 帮助页共用，防止口径漂移）。 */
export const EXPLAIN = {
  stars: {
    zh: "星级按本轮各题参考分均值评定：≥85 得 3 星，≥70 得 2 星，完成即得 1 星。只和自己比，不和同学排名。",
    en: "Stars are based on your average score this round: 85+ earns 3 stars, 70+ earns 2, and finishing earns 1. Compare only with yourself, never with classmates.",
  },
  xp: {
    zh: "每完成一题得 10 XP，每颗星加 5 XP，连续练习 3 天及以上每天再奖 10 XP。",
    en: "Earn 10 XP per completed item and 5 XP per star; practice 3+ days in a row for a 10 XP daily bonus.",
  },
  streak: {
    zh: "在练习日内连续完成练习的累计天数，中断后重新开始。",
    en: "Consecutive days with completed practice; it restarts after a break.",
  },
  badges: {
    zh: "完成特定练习目标时获得（如首次开口、坚持 3 天等），只在「我的成长」展示。",
    en: "Earned by reaching practice milestones (first recording, 3-day streak, etc.), shown only in My Growth.",
  },
  score: {
    zh: "参考分由 AI 语音评测生成，用于指出改进方向，不是考试成绩或官方等级。",
    en: "Reference scores are generated by AI speech assessment to point out improvement areas — not exam grades or official levels.",
  },
} as const satisfies Record<string, BiString>

/** 题型 → 展示名（学生端/教师端/结果页/发布历史共用，防文案分叉）。 */
export const ITEM_TYPE_LABELS: Record<string, BiString> = {
  passage: TERMS.typeReading,
  repeat: TERMS.typeRepeat,
  question: TERMS.typeQa,
}
