/**
 * 全站术语单一事实源（2026-09 术语统一；2026-09-30 起双语化）。
 *
 * 面向用户的新文案一律从这里取词，避免同一概念再次出现多种叫法。
 * 所有值是 BiString：组件里用 useI18n().t(TERMS.xxx) 取当前语言。
 * 人读版本（含取舍原因）见仓库 CLAUDE.md「术语表」章节。
 */
import type { BiString } from "./bi.ts"

export const TERMS = {
  /** Unit：课堂指派与学生自主练习的基本单位 */
  unit: { zh: "单元", en: "Unit" },
  /** Unit.topic：单元的主题（如「宠物」） */
  topic: { zh: "主题", en: "Topic" },
  /** Passage：朗读/复述用的英文材料 */
  passage: { zh: "篇目", en: "Passage" },
  /** 三种题型（全端统一名称） */
  typeReading: { zh: "文章朗读", en: "Read Aloud" },
  typeRepeat: { zh: "听句复述", en: "Listen & Repeat" },
  typeQa: { zh: "情景问答", en: "Scenario Q&A" },
  /** 第四种题型：无作答的纯文字引导页（学生点「继续」进入下一题） */
  typeInstruction: { zh: "题目说明", en: "Instructions" },
  /** 学生端每日练习入口（与导航一致） */
  todayPractice: { zh: "今日练习", en: "Today's Practice" },
  /** 老师未发布统一内容时，学生按单元顺序自行练习 */
  selfPractice: { zh: "自主练习", en: "Self Practice" },
  /** 老师把单元下发给全班的动作（教师端按钮用「发布」） */
  publish: { zh: "发布", en: "Publish" },
  /** 词汇学习模块（学生端导航与页面标题） */
  vocabLearning: { zh: "词汇学习", en: "Vocabulary" },
  /** 词汇任务（教师发布给全班的单词练习） */
  vocabTask: { zh: "词汇任务", en: "Vocabulary Task" },
  /** 词库（教师/管理端维护的单词集合） */
  vocabBook: { zh: "词库", en: "Word Book" },
  /** 错词本（学生首答判错的词自动归集） */
  wrongWords: { zh: "错词本", en: "Wrong Words" },
  /** 错词专项复习（错词本直接进入、限定当前可练范围的练习） */
  vocabReview: { zh: "错词复习", en: "Wrong-word Review" },
  /** 练习记录（个人历史列表与正确率趋势） */
  practiceRecords: { zh: "练习记录", en: "Practice Records" },
  /** 混入错词（自主练习选项：按 30% 目标混入所选词库内的历史错词） */
  mixWrongWords: { zh: "混入错词", en: "Mix in Wrong Words" },
  /** 词汇测验（限时、服务端计时的测验模式） */
  vocabQuiz: { zh: "词汇测验", en: "Vocabulary Quiz" },
  /** 考试时长（个人计时） */
  quizDuration: { zh: "考试时长", en: "Time limit" },
  /** 及格线（百分制） */
  passLine: { zh: "及格线", en: "Pass line" },
  /** 开始测验（规则页明确动作：点击后才计时） */
  startQuiz: { zh: "开始测验", en: "Start quiz" },
  /** 交卷（主动终结答卷） */
  submitQuiz: { zh: "交卷", en: "Submit" },
  /** 已交卷（主动交卷的终态） */
  quizSubmitted: { zh: "已交卷", en: "Submitted" },
  /** 超时结束（服务端到时结算的终态） */
  quizTimedOut: { zh: "超时结束", en: "Timed out" },
  /** 补考（教师单独授权一次） */
  quizRetake: { zh: "补考", en: "Retake" },
  /** 公布成绩 / 公布答案（教师分别控制） */
  publishGrades: { zh: "公布成绩", en: "Publish grades" },
  publishAnswers: { zh: "公布答案", en: "Publish answers" },
  /** 切屏次数（仅记录的异常事件） */
  tabSwitchCount: { zh: "切屏次数", en: "Tab switches" },
  /** AI 备课（教师生成词条草稿） */
  aiPrep: { zh: "AI 备课", en: "AI Prep" },
  /** AI 生成草稿（按钮） */
  aiGenerateDrafts: { zh: "AI 生成词条草稿", en: "Generate drafts with AI" },
  /** 单词讲解（学生，AI） */
  aiWordExplanation: { zh: "AI 讲解", en: "AI explain" },
  /** 学情分析（单次，AI） */
  aiSessionInsight: { zh: "本次学情分析", en: "Analyze this round" },
  /** 整体学习建议（AI） */
  aiOverallInsight: { zh: "整体学习建议", en: "Overall suggestions" },
  /** 重新生成 */
  aiRegenerate: { zh: "重新生成", en: "Regenerate" },
  /** 看义拼词（出题方式） */
  promptMeaning: { zh: "看义拼词", en: "Spell from Meaning" },
  /** 听音拼词（出题方式） */
  promptAudio: { zh: "听音拼词", en: "Spell from Audio" },
  /** 五级词库（口语与背单词共用的统一分级数据源） */
  vocabLevels: { zh: "五级词库", en: "Leveled Word Source" },
  /** 用词来源级别（口语命中统计标题；明确不是能力等级） */
  wordSourceLevel: {
    zh: "用词来源级别",
    en: "Word Source Levels",
  },
  /** 用词来源级别的口径说明（触点小字共用，防口径漂移） */
  wordSourceLevelNote: {
    zh: "按五级词库统计本次实际用到的词来自哪些级别；词表命中只说明用词来源，不代表能力等级。",
    en: "Shows which levels the words you actually used come from. Wordlist hits indicate word source only — not a proficiency level.",
  },
  /** 系统给学生的分数口径：不是考试成绩 */
  score: { zh: "参考分", en: "Reference Score" },
  /** 学生成长页（导航与页面标题一致） */
  growthPage: { zh: "我的成长", en: "My Growth" },
  /** 教师端查看学生历史曲线的页面 */
  trailPage: { zh: "进步轨迹", en: "Progress Trail" },
} as const satisfies Record<string, BiString>

/** 激励规则解释（触点小字 / Tooltip / 帮助页共用，防止口径漂移）。 */
export const EXPLAIN = {
  stars: {
    zh: "星级按本轮各题参考分均值评定：≥85 得 3 星，≥70 得 2 星，完成即得 1 星。只和自己比，不和同学排名。",
    en: "Stars are based on your average score this round: 85+ earns 3 stars, 70+ earns 2, and finishing earns 1. Compare only with yourself, never with classmates.",
  },
  xp: {
    zh: "每完成一题得 10 XP，每颗星加 5 XP，连续练习 3 天及以上每天再奖 10 XP。",
    en: "Earn 10 XP per completed item and 5 XP per star; practice 3+ days in a row for a 10 XP daily bonus.",
  },
  streak: {
    zh: "在练习日内连续完成练习的累计天数，中断后重新开始。",
    en: "Consecutive days with completed practice; it restarts after a break.",
  },
  badges: {
    zh: "完成特定练习目标时获得（如首次开口、坚持 3 天等），只在「我的成长」展示。",
    en: "Earned by reaching practice milestones (first recording, 3-day streak, etc.), shown only in My Growth.",
  },
  score: {
    zh: "参考分由 AI 语音评测生成，用于指出改进方向，不是考试成绩或官方等级。",
    en: "Reference scores are generated by AI speech assessment to point out improvement areas — not exam grades or official levels.",
  },
} as const satisfies Record<string, BiString>

/** 题型 → 展示名（学生端/教师端/结果页/发布历史共用，防文案分叉）。 */
export const ITEM_TYPE_LABELS: Record<string, BiString> = {
  passage: TERMS.typeReading,
  repeat: TERMS.typeRepeat,
  question: TERMS.typeQa,
  instruction: TERMS.typeInstruction,
}

/** 五级固定顺序（越靠前越容易）；与后端 VOCAB_LEVEL_ORDER 一致 */
export const VOCAB_LEVEL_ORDER = [
  "KET",
  "PET",
  "ACADEMIC",
  "CET4",
  "IELTS_TOEFL",
] as const

export type VocabLevel = (typeof VOCAB_LEVEL_ORDER)[number]

/** 级别代码 → 双语名称 */
export const VOCAB_LEVEL_LABELS: Record<VocabLevel, BiString> = {
  KET: { zh: "KET 词汇", en: "KET" },
  PET: { zh: "PET 词汇", en: "PET" },
  ACADEMIC: { zh: "学术词汇", en: "Academic" },
  CET4: { zh: "四级词汇", en: "CET-4" },
  IELTS_TOEFL: { zh: "雅思&托福词汇", en: "IELTS & TOEFL" },
}

/** 分级题型训练：考试式题型（与级别两维分别建模） */
export const EXAM_KIND_LABELS: Record<string, BiString> = {
  toefl_lnr: { zh: "TOEFL · 听令复述", en: "TOEFL · Listen & Repeat" },
  interview: { zh: "TOEFL · 情景访谈", en: "TOEFL · Take an Interview" },
  ielts_p1: { zh: "IELTS · Part 1", en: "IELTS · Part 1" },
  ielts_p2: { zh: "IELTS · Part 2", en: "IELTS · Part 2" },
  ielts_p3: { zh: "IELTS · Part 3", en: "IELTS · Part 3" },
}

/** 题型级别徽标的级别名（复用五级） */
export const EXAM_LEVEL_LABELS: Record<string, BiString> = VOCAB_LEVEL_LABELS

/** 课堂考试反馈免责声明（触点共用，防口径漂移） */
export const EXAM_PRACTICE_NOTE = {
  zh: "这是课堂分级练习反馈，帮助练习考试题型；不是官方考试成绩，也不预测考试得分。",
  en: "This is classroom practice feedback for exam-style tasks. It is not an official exam score and does not predict exam results.",
} as const satisfies BiString

/** 表达用途（句型推荐分类） */
export const FRAME_PURPOSE_LABELS: Record<string, BiString> = {
  opinion: { zh: "表达观点", en: "Opinion" },
  reason: { zh: "给出理由", en: "Reason" },
  example: { zh: "举例说明", en: "Example" },
  compare: { zh: "比较对比", en: "Compare" },
  describe: { zh: "描述人/物/事", en: "Describe" },
  past: { zh: "回忆经历", en: "Past experience" },
  future: { zh: "展望计划", en: "Plans ahead" },
}

/** 「首答正确」口径：按每题第一次作答计，重试不冲高（练习页/成长页触点共用） */
export const EXPLAIN_FIRST_TRY = {
  zh: "首答正确按每题第一次作答计算，重试不改变统计。",
  en: "First-try correct counts each item's first answer; retries don't change the stats.",
} as const satisfies BiString

/** 词列表「?」遮盖的说明（词汇首页触点共用） */
export const EXPLAIN_MASKED_WORDS = {
  zh: "作答后这里会显示单词；先看中文释义，回忆拼写。",
  en: "Words appear here after you answer. Read the meaning first and recall the spelling.",
} as const satisfies BiString

/** 错词本口径：不删除、非掌握度评估（词汇首页/记录页触点共用） */
export const EXPLAIN_WRONG_WORDS_POLICY = {
  zh: "错词不会因为答对一次就移除。这里分开展示历史错误次数、最近独立首答和最近练对时间，只用于安排复习，不是科学掌握度评估。",
  en: "A word stays in this book even after you get it right once. Historical misses, your latest first try, and your latest correct answer are shown separately — for review planning only, not a scientific mastery score.",
} as const satisfies BiString

/** 首答正确率口径：分母为已答题数（自主练习报告/记录页触点共用） */
export const EXPLAIN_FIRST_TRY_ACCURACY = {
  zh: "首答正确率 = 首答正确的题数 ÷ 已答题数。没答的题不计入分母，也不算作答错。",
  en: "First-try accuracy = items correct on the first try ÷ items answered. Unanswered items are excluded — not counted as wrong.",
} as const satisfies BiString

/** 轮次时间口径：只展示起止时间，不折算学习时长（报告页触点共用） */
export const EXPLAIN_ROUND_TIMES = {
  zh: "这里展示本轮的开始与结束时间。不折算「学习时长」——离开页面的时间无法区分，不做虚假统计。",
  en: "This shows the round's start and end times. No study-duration is derived — time away from the page can't be separated out, so we don't fake it.",
} as const satisfies BiString

/** 混入错词选项说明（词库浏览页触点共用） */
export const EXPLAIN_MIX_WRONG = {
  zh: "开启后，本轮约 30% 的词来自你在本词库拼错过的词（最近错的优先）；错词不够就用其他词补足。题单和顺序在开始后固定。",
  en: "When on, about 30% of this round comes from words you previously misspelled in this book (most recent misses first); other words fill the rest. The list and its order are fixed once the round starts.",
} as const satisfies BiString

/** 测验规则口径（学生规则页/作答页触点共用） */
export const EXPLAIN_QUIZ_RULES = {
  zh: "点「开始测验」才开始计时；时间以服务器为准，刷新或换设备不会重置。每题只能提交一次；到时间会自动交卷。",
  en: "The timer starts only when you tap Start. Time is kept by the server — refreshing or switching devices won't reset it. Each item accepts one submission; time-up auto-submits.",
} as const satisfies BiString

/** 测验切屏口径（教师端触点共用） */
export const EXPLAIN_QUIZ_TAB_SWITCH = {
  zh: "切屏只记录次数供教师参考，不自动认定作弊。",
  en: "Tab switches are counted for teacher reference only — never treated as cheating automatically.",
} as const satisfies BiString

/** AI 输出口径（讲解/学情触点共用；红线：判分是确定性规则） */
export const EXPLAIN_AI_CONTENT = {
  zh: "以下内容由 AI 生成，仅供参考，可能不准确；拼写对错始终由系统规则判定。",
  en: "AI-generated content for reference only and may be inaccurate. Spelling right/wrong is always decided by the system's rules.",
} as const satisfies BiString

/** 学情范围口径（AI 学情触点共用） */
export const EXPLAIN_AI_SCOPE = {
  zh: "分析只使用你的真实作答记录；薄弱词都有对应证据（你的拼写 vs 正确拼写）。",
  en: "Analysis uses only your real answers; every weak word comes with evidence (your spelling vs the correct one).",
} as const satisfies BiString

/** 测验公布口径（学生端提交状态/成绩触点共用） */
export const EXPLAIN_QUIZ_PUBLISH = {
  zh: "交卷后成绩与答案由老师分别公布；公布前这里只显示提交状态，不显示对错。",
  en: "Grades and answers are released separately by your teacher. Until then, only your submission status shows here — no right/wrong.",
} as const satisfies BiString
